-- Read-only verification. Every returned value must be true before production intake is enabled.
SELECT
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='014_production_intake_008_baseline' AND checksum='59c86bfe2ac730a4ded2e4ec8cb3cfe590367614c9fbba9dace126a0cd319ce2') AS migration_version_recorded,
  to_regclass('venture_private.member_crm_master_profiles') IS NOT NULL AS crm_master_table_exists,
  EXISTS(SELECT 1 FROM pg_class WHERE oid='venture_private.member_crm_master_profiles'::regclass AND relrowsecurity AND relforcerowsecurity) AS crm_rls_forced,
  NOT EXISTS(SELECT 1 FROM pg_class table_acl CROSS JOIN LATERAL aclexplode(coalesce(table_acl.relacl,acldefault('r',table_acl.relowner))) privilege WHERE table_acl.oid='venture_private.member_crm_master_profiles'::regclass AND privilege.grantee=0 AND privilege.privilege_type='SELECT') AS public_cannot_read_crm,
  to_regprocedure('public.venture_stage_governed_import_chunk(text,jsonb)') IS NOT NULL AS chunk_rpc_exists,
  to_regprocedure('public.venture_finalize_governed_import_batch(text)') IS NOT NULL AS finalize_rpc_exists,
  to_regprocedure('public.venture_upsert_activity(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,text,text,jsonb,jsonb,text,text,text,text,text)') IS NOT NULL AS activity_rpc_exists,
  NOT EXISTS(SELECT 1 FROM pg_proc function_acl CROSS JOIN LATERAL aclexplode(coalesce(function_acl.proacl,acldefault('f',function_acl.proowner))) privilege WHERE function_acl.oid='public.venture_upsert_activity(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,text,text,jsonb,jsonb,text,text,text,text,text)'::regprocedure AND privilege.grantee=0 AND privilege.privilege_type='EXECUTE') AS public_cannot_upsert_activity,
  CASE WHEN EXISTS(SELECT 1 FROM pg_roles WHERE rolname='anon') THEN NOT has_function_privilege('anon','public.venture_upsert_activity(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,text,text,jsonb,jsonb,text,text,text,text,text)','EXECUTE') ELSE true END AS anon_cannot_upsert_activity,
  CASE WHEN EXISTS(SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN NOT has_function_privilege('authenticated','public.venture_upsert_activity(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,text,text,jsonb,jsonb,text,text,text,text,text)','EXECUTE') ELSE true END AS authenticated_cannot_upsert_activity,
  CASE WHEN EXISTS(SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN has_function_privilege('service_role','public.venture_upsert_activity(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,text,text,jsonb,jsonb,text,text,text,text,text)','EXECUTE') ELSE false END AS service_role_can_upsert_activity,
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='venture_activities_public' AND column_name='replay_available') AS public_view_has_safe_replay_flag,
  NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='venture_activities_public' AND column_name IN ('meeting_link_ciphertext','replay_link_ciphertext','minutes_object_key_ciphertext','recording_object_key_ciphertext')) AS public_view_has_no_private_locators;
