'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {resolveAdminGovernanceConfig}=require('../src/auth/admin-governance-config');const {AdminGovernanceService}=require('../src/auth/admin-governance-service');
const production={ADMIN_GOVERNANCE_ENABLED:'true',NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',FORMAL_ADMIN_AUTH_ENABLED:'true',CLOUDBASE_PG_MIGRATIONS_APPLIED:'009_admin_governance',ADMIN_BOOTSTRAP_MODE:'preprovisioned_subject_hash_once',ADMIN_ROLE_CHANGE_MODE:'two_person',ADMIN_AUDIT_MODE:'redacted_metadata_only'};
const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
function harness(){const calls=[],sessionService={authorizeAction:async input=>{calls.push(['authorize',input]);if(input.excludedActorIds?.includes('admin-requester'))throw Object.assign(new Error('separation'),{code:'SEPARATION_OF_DUTIES_REQUIRED'});return {sessionId:'session-requester',userId:'admin-requester',authorizationId:'authorization-fixture'}},resolveRequest:async()=>({verified:true,userId:'auditor-fixture',sessionId:'session-auditor',permissions:['audit.read']})};const repository={bootstrap:async input=>{calls.push(['bootstrap',input]);return {status:'bootstrapped',self_registration:false}},requestRoleChange:async input=>{calls.push(['request',input]);return {request_id:'change-fixture',status:'pending'}},approveRoleChange:async input=>{calls.push(['approve',input]);return {request_id:input.requestId,status:'applied',sessions_revoked:true}},listRedactedAudit:async input=>{calls.push(['audit',input]);return [{occurred_at:'2026-08-05T00:00:00Z',actor_reference:'hash',action:'admin.role_change.apply',subject_reference:'hash2',sensitive_data_included:false,phone:'must-not-leak'}]}};return {calls,service:new AdminGovernanceService({config:resolveAdminGovernanceConfig(production),sessionService,repository,identityVerifier:{verify:async assertion=>assertion==='valid-assertion'?{verified:true,provider:'corporate_sso',subject:'synthetic-subject'}:null},hashSubject:identity=>hash(`${identity.provider}:${identity.subject}`),hashBootstrapTicket:hash})}}
test('governance is explicit, production-only and staging fails closed',()=>{assert.equal(resolveAdminGovernanceConfig({}).enabled,false);assert.throws(()=>resolveAdminGovernanceConfig({ADMIN_BOOTSTRAP_MODE:'preprovisioned_subject_hash_once'}),/未启用/);assert.throws(()=>resolveAdminGovernanceConfig({...production,DEMO_DATA_ONLY:'true'}),/staging/);assert.equal(resolveAdminGovernanceConfig(production).safeSummary.selfRegistration,false)});
test('bootstrap accepts only server-verified identity plus one-time proof and sends hashes only',async()=>{const {service,calls}=harness();await assert.rejects(()=>service.bootstrap({identityAssertion:'invalid',bootstrapTicket:'A'.repeat(40)}),error=>error.code==='ADMIN_BOOTSTRAP_IDENTITY_REQUIRED');const result=await service.bootstrap({identityAssertion:'valid-assertion',bootstrapTicket:'A'.repeat(40)});assert.equal(result.self_registration,false);const serialized=JSON.stringify(calls);assert.equal(serialized.includes('synthetic-subject'),false);assert.equal(serialized.includes('A'.repeat(40)),false);assert.match(calls[0][1].subjectHash,/^[0-9a-f]{64}$/)});
test('role changes require server authorization and exclude target, requester and approver overlap',async()=>{const {service,calls}=harness();await assert.rejects(()=>service.requestRoleChange({targetUserId:'admin-requester',roleCode:'reviewer',action:'grant',idempotencyKey:'role-change-1'}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED');const requested=await service.requestRoleChange({targetUserId:'target-fixture',roleCode:'reviewer',action:'grant',idempotencyKey:'role-change-2'});assert.equal(requested.status,'pending');const approved=await service.approveRoleChange({changeRequest:{id:'change-fixture',status:'pending',requester_id:'other-requester',target_user_id:'target-fixture'},idempotencyKey:'role-change-3'});assert.equal(approved.sessions_revoked,true);const approvalGate=calls.find(call=>call[0]==='authorize'&&call[1].idempotencyKey==='role-change-3')[1];assert.deepEqual(approvalGate.excludedActorIds,['other-requester','target-fixture'])});
test('audit query is permission-gated, bounded and explicitly non-exportable',async()=>{const {service}=harness();const result=await service.listAudit({request:{},limit:50});assert.equal(result.redacted,true);assert.equal(result.exportAvailable,false);assert.equal(JSON.stringify(result).includes('phone'),false);await assert.rejects(()=>service.listAudit({request:{},limit:1000}),error=>error.code==='ADMIN_AUDIT_LIMIT_INVALID')});
test('009 migration has one-time bootstrap, two-person approval, immediate revocation and no client grants',()=>{const sql=fs.readFileSync(path.join(__dirname,'../db/migrations/009_admin_governance.sql'),'utf8');for(const term of ['status=\'used\'','system admin already bootstrapped','independent role approval required','admin_sessions SET status=\'revoked\'','admin_action_authorizations SET status=\'rejected\'','venture_read_redacted_admin_audit','sensitive_data_included'])assert.ok(sql.includes(term),term);assert.match(sql,/^\s*(?:--[^\n]*\n)*BEGIN;/);assert.match(sql,/COMMIT;\s*$/);const grantBlock=sql.match(/DO \$admin_governance_grants\$[\s\S]*?END \$admin_governance_grants\$;/)?.[0]||'';assert.match(grantBlock,/THEN EXECUTE 'GRANT EXECUTE ON FUNCTION/);assert.match(grantBlock,/THEN EXECUTE 'REVOKE ALL ON FUNCTION/);assert.doesNotMatch(grantBlock,/THEN\s+(?:GRANT|REVOKE)\b/i);assert.doesNotMatch(sql,/GRANT EXECUTE[\s\S]{0,200} TO (?:anon|authenticated)/i);assert.doesNotMatch(sql,/raw_subject|phone|wechat|protected_payload/i)});
