'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {GatewayCatalogReadService,assertGatewayCatalogContractReady}=require('../src/persistence/catalog-service');

const activeMember={id:'member-fixture',userStatus:'active',status:'active',startsAt:'2020-01-01T00:00:00.000Z',endsAt:'2099-01-01T00:00:00.000Z',crmVerificationStatus:'verified',latestPaymentEvidenceStatus:'verified',latestValidPaymentAt:'2020-01-02T00:00:00.000Z',groupStatus:'in_group'};
const expiredMember={...activeMember,status:'expired'};
function repository(overrides={}){return {kind:'cloudbase_gateway',config:{mode:'cloudbase_gateway',enabled:true,runtimeEnvironment:'production',catalogReadsEnabled:true},listPublishedResources:async()=>[],listPublicActivities:async()=>[],...overrides}}
function service({repo=repository(),member=activeMember,events=[]}={}){return new GatewayCatalogReadService({repository:repo,identityProvider:'external_verified_session',featureEnabled:true,memberResolver:async()=>{events.push('identity');return member}})}

test('catalog contract refuses memory repositories, non-production, missing identity mapping and disabled feature',()=>{assert.throws(()=>assertGatewayCatalogContractReady({repository:{kind:'memory_demo'},identityProvider:'external_verified_session',featureEnabled:true}),/cloudbase_gateway/);assert.throws(()=>assertGatewayCatalogContractReady({repository:repository({config:{mode:'cloudbase_gateway',enabled:true,runtimeEnvironment:'test',catalogReadsEnabled:true}}),identityProvider:'external_verified_session',featureEnabled:true}),/production/);assert.throws(()=>assertGatewayCatalogContractReady({repository:repository(),identityProvider:'demo_header',featureEnabled:true}),/身份映射/);assert.throws(()=>assertGatewayCatalogContractReady({repository:repository(),identityProvider:'external_verified_session',featureEnabled:false}),/尚未启用/)});
test('member identity and active membership gates run before any gateway fetch',async()=>{const events=[];const repo=repository({listPublishedResources:async()=>{events.push('fetch');return []}});await assert.rejects(()=>service({repo,member:expiredMember,events}).listResources({session:'fixture'}),error=>error.code==='MEMBERSHIP_REQUIRED');assert.deepEqual(events,['identity'])});
test('active member reaches the fixed repository only after the gate and receives whitelisted fields',async()=>{const events=[];const repo=repository({listPublishedResources:async()=>{events.push('fetch');return [{id:'r1',title:'匿名目录资料',summary:'安全摘要',type:'report',tags:['行业'],access_level:'active_member',mobile_section:'reports',preview_status:'preview_not_configured',download_enabled:false,published_at:'2026-01-01',updated_at:'2026-01-02',private_object_key_ciphertext:'must-not-leak'}]}});const result=await service({repo,events}).listResources({verifiedSession:'fixture'});assert.deepEqual(events,['identity','fetch']);assert.equal(result[0].title,'匿名目录资料');assert.equal(result[0].viewEnabled,true);assert.equal(JSON.stringify(result).includes('private_object'),false);assert.equal(JSON.stringify(result).includes('must-not-leak'),false)});
test('gateway failure becomes a generic 503 without response or credential leakage and never falls back',async()=>{const repo=repository({listPublicActivities:async()=>{throw new Error('upstream body contains fixture-server-key and private row')}});const error=await service({repo}).listActivities({verifiedSession:'fixture'}).catch(x=>x);assert.equal(error.statusCode,503);assert.equal(error.code,'CATALOG_PERSISTENCE_UNAVAILABLE');assert.equal(error.message,'资料与活动目录暂时不可用');assert.doesNotMatch(JSON.stringify(error),/fixture-server-key|private row/)});
test('activity directory output cannot include meeting links or registration facts',async()=>{const repo=repository({listPublicActivities:async()=>[{id:'a1',title:'匿名公开活动',description:'活动说明',format:'online',starts_at:'2026-02-01',ends_at:'2026-02-01',registration_ends_at:'2026-01-31',category:'sharing',city:'示例城',venue:'线上',status:'registration_open',created_at:'2026-01-01',meeting_link_ciphertext:'must-not-leak',registered:true}]});const result=await service({repo}).listActivities({verifiedSession:'fixture'});assert.equal(result[0].title,'匿名公开活动');assert.equal(JSON.stringify(result).includes('meeting'),false);assert.equal('registered' in result[0],false)});
