'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {resolvePersistenceConfig}=require('../src/persistence/config');
const {MAX_REQUEST_BYTES,manifestChecksum,verifyCapabilityManifest,resolveCloudBaseMemberBindingTransportConfig,CloudBaseVerifiedRpcClient,PreparedCloudBaseMemberBindingTransport}=require('../src/persistence/cloudbase-member-binding-transport');

const cloudbase={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_ENV_ID:'fixture-env',CLOUDBASE_PG_SERVER_API_KEY:'fixture-server-only-key',CLOUDBASE_PG_REGION:'ap-shanghai',CLOUDBASE_PG_MIGRATIONS_APPLIED:'008_admin_session_rbac',CLOUDBASE_PG_CREDENTIAL_PURPOSE:'server_runtime',CLOUDBASE_MEMBER_BINDING_RPC_MIGRATION_APPLIED:'012_member_binding_rpc_008_baseline'};
function manifest(){const value={version:'member-binding-rpc-v1',baseline:'012_member_binding_rpc_008_baseline',platform:'cloudbase_postgrest_rpc',rpc:{resolveExactCrmMatch:'venture_fixture_resolve_exact_match',persistCandidate:'venture_fixture_persist_candidate',listPending:'venture_fixture_list_pending',bindIdentityIdempotently:'venture_fixture_bind_identity',rejectCandidate:'venture_fixture_reject_candidate'},evidence:{source:'cloudbase_readonly_contract_check',verifiedAt:'2026-08-11T00:00:00.000Z',rpcExistence:true,serviceRoleExecute:true,publicExecuteDenied:true,anonExecuteDenied:true,authenticatedExecuteDenied:true,transactionalIdentityWrite:true,idempotencyKeyUnique:true,safeResponseProjection:true}};value.checksum=manifestChecksum(value);return value}
function enabledConfig(overrides={}){const capabilityManifest=manifest(),environment={...cloudbase,FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'false',CLOUDBASE_MEMBER_BINDING_WRITES_ENABLED:'true',CLOUDBASE_MEMBER_BINDING_TRANSPORT:'verified_postgrest_rpc',CLOUDBASE_MEMBER_BINDING_CAPABILITY_SHA256:capabilityManifest.checksum,...overrides};return resolveCloudBaseMemberBindingTransportConfig(environment,{persistenceConfig:resolvePersistenceConfig(environment),capabilityManifest})}
const response=value=>({ok:true,status:200,headers:{get:name=>name==='content-type'?'application/json':null},text:async()=>JSON.stringify(value)});

test('write transport is disabled by default and stale partial configuration is rejected',()=>{assert.equal(resolveCloudBaseMemberBindingTransportConfig({}).enabled,false);assert.throws(()=>resolveCloudBaseMemberBindingTransportConfig({CLOUDBASE_MEMBER_BINDING_TRANSPORT:'verified_postgrest_rpc'}),/拒绝静默保留/);assert.throws(()=>resolveCloudBaseMemberBindingTransportConfig({CLOUDBASE_MEMBER_BINDING_RPC_MIGRATION_APPLIED:'012_member_binding_rpc_008_baseline'}),/拒绝静默保留/);assert.throws(()=>enabledConfig({NODE_ENV:'test'}),/production/);assert.throws(()=>enabledConfig({DEMO_DATA_ONLY:'true'}),/匿名 staging|非 demo/);assert.throws(()=>enabledConfig({FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'true'}),/继续保持 false/);assert.throws(()=>enabledConfig({CLOUDBASE_PG_CREDENTIAL_PURPOSE:'migrator'}),/server_runtime|持久化/)});

test('capability manifest requires deployed RPC evidence, future 012 baseline and checksum',()=>{const valid=manifest();assert.equal(verifyCapabilityManifest(valid).checksum,valid.checksum);for(const mutate of [value=>value.evidence.anonExecuteDenied=false,value=>value.baseline='008_admin_session_rbac',value=>value.rpc.persistCandidate=value.rpc.resolveExactCrmMatch,value=>value.checksum='a'.repeat(64)]){const value=manifest();mutate(value);assert.throws(()=>verifyCapabilityManifest(value))}assert.throws(()=>enabledConfig({CLOUDBASE_MEMBER_BINDING_RPC_MIGRATION_APPLIED:'008_admin_session_rbac'}),/012_member_binding_rpc_008_baseline/);const capabilityManifest=manifest();assert.throws(()=>resolveCloudBaseMemberBindingTransportConfig({...cloudbase,FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'false',CLOUDBASE_MEMBER_BINDING_WRITES_ENABLED:'true',CLOUDBASE_MEMBER_BINDING_TRANSPORT:'verified_postgrest_rpc',CLOUDBASE_MEMBER_BINDING_CAPABILITY_SHA256:'b'.repeat(64)},{persistenceConfig:resolvePersistenceConfig(cloudbase),capabilityManifest}),/未匹配/)});

test('verified RPC client uses only manifest-mapped CloudBase PostgREST functions and server API key',async()=>{const calls=[],config=enabledConfig(),client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});return response({candidateCount:0})}});const result=await client.call('resolveExactCrmMatch',{subjectHash:'a'.repeat(64)});assert.equal(result.candidateCount,0);assert.equal(calls[0].url.origin,'https://fixture-env.api.tcloudbasegateway.com');assert.equal(calls[0].url.pathname,'/v1/rdb/rest/rpc/venture_fixture_resolve_exact_match');assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].options.redirect,'error');assert.equal(calls[0].options.headers.authorization,'Bearer fixture-server-only-key');assert.equal(calls[0].url.href.includes('fixture-server-only-key'),false);assert.equal(calls[0].options.body.includes('fixture-server-only-key'),false);assert.equal(calls[0].url.pathname.includes('external_identity_bindings'),false);await assert.rejects(()=>client.call('directTableInsert',{}),/固定白名单/);const readiness=client.safeReadiness();assert.equal(readiness.directTableWrites,false);assert.equal(readiness.credentialsExposed,false)});

test('prepared transport maps all logical operations to one-json-argument RPCs without inventing table endpoints',async()=>{const calls=[],config=enabledConfig(),client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async(url,options)=>{calls.push({path:new URL(url).pathname,body:JSON.parse(options.body)});return response(calls.length===3?[]:{ok:true})}}),transport=new PreparedCloudBaseMemberBindingTransport({client});await transport.resolveExactCrmMatch({subjectHash:'a'.repeat(64)});await transport.persistCandidate({candidate:'fixture'});await transport.listPending({limit:10});await transport.bindIdentityIdempotently({candidateId:'fixture'});await transport.rejectCandidate({candidateId:'fixture'});assert.deepEqual(calls.map(value=>value.path),config.manifest.rpc&&['resolveExactCrmMatch','persistCandidate','listPending','bindIdentityIdempotently','rejectCandidate'].map(key=>`/v1/rdb/rest/rpc/${config.manifest.rpc[key]}`));assert.deepEqual(calls[0].body,{p_request:{subjectHash:'a'.repeat(64)}});assert.deepEqual(calls[2].body,{p_request:{limit:10}});assert.equal(calls.some(value=>!value.path.includes('/rpc/')),false);assert.equal(transport.safeReadiness().runtimeEnabled,false);assert.equal(transport.safeReadiness().routesEnabled,false)});

test('HTTP, timeout, oversized and invalid JSON failures are redacted',async()=>{const config=enabledConfig();let client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async()=>({ok:false,status:403,headers:{get:()=>null},text:async()=>'{"secret":"private-row"}'})});let error=await client.call('listPending',{}).catch(value=>value);assert.equal(error.code,'CLOUDBASE_MEMBER_BINDING_RPC_UNAVAILABLE');assert.doesNotMatch(JSON.stringify(error),/private-row|fixture-server-only-key/);client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async()=>{const failure=new Error('raw network secret');failure.name='AbortError';throw failure}});error=await client.call('listPending',{}).catch(value=>value);assert.equal(error.code,'CLOUDBASE_MEMBER_BINDING_RPC_TIMEOUT');assert.doesNotMatch(JSON.stringify(error),/raw network/);let read=false;client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async()=>({ok:true,headers:{get:name=>name==='content-length'?'999999':null},text:async()=>{read=true;return '[]'}})});await assert.rejects(()=>client.call('listPending',{}),failure=>failure.code==='CLOUDBASE_MEMBER_BINDING_RPC_RESPONSE_TOO_LARGE');assert.equal(read,false);client=new CloudBaseVerifiedRpcClient({config,fetchImpl:async()=>({ok:true,headers:{get:()=>null},text:async()=>'<html>'})});await assert.rejects(()=>client.call('listPending',{}),failure=>failure.code==='CLOUDBASE_MEMBER_BINDING_RPC_INVALID_RESPONSE')});
test('request bodies are bounded before network access',async()=>{let calls=0;const client=new CloudBaseVerifiedRpcClient({config:enabledConfig(),fetchImpl:async()=>{calls++;return response({})}});await assert.rejects(()=>client.call('persistCandidate',{padding:'x'.repeat(MAX_REQUEST_BYTES)}),error=>error.code==='CLOUDBASE_MEMBER_BINDING_RPC_REQUEST_TOO_LARGE');await assert.rejects(()=>client.call('persistCandidate',[]),error=>error.code==='CLOUDBASE_MEMBER_BINDING_RPC_REQUEST_INVALID');assert.equal(calls,0)});
