'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),childProcess=require('node:child_process');
const root=path.join(__dirname,'../..'),dir=path.join(root,'server/db/future/member-binding-rpc');
const read=file=>fs.readFileSync(path.join(dir,file),'utf8'),sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
const manifest=JSON.parse(read('manifest.json'));
test('future package is isolated, unapplied and pins canonical 004/008 byte-for-byte',()=>{assert.equal(manifest.status,'future_not_applied');assert.equal(manifest.runtimeEnablementAllowed,false);assert.equal(sha('server/db/migrations/004_wechat_identity_entitlement.sql'),'89651f91578a44d1f5fd78e8039c7ded587bbfae3a18764ee4bb3b2090d5a621');assert.equal(sha('server/db/migrations/008_admin_session_rbac.sql'),'1d29f1997e3d63322ae56a0fef78b559d41028e2d278527ffdc0d51e1652bd3d');for(const [file,expected] of Object.entries(manifest.checksums))assert.equal(sha(file),expected)});
test('five RPCs use one json argument, service-role self check and deny all client roles',()=>{const sql=read('012_member_binding_rpc_008_baseline.sql'),rpcs=Object.values(manifest.rpc);assert.equal(rpcs.length,5);assert.equal(new Set(rpcs).size,5);assert.match(sql,/current_setting\('request\.jwt\.claims',true\)/);assert.match(sql,/claims->>'role'<>'service_role'/);for(const rpc of rpcs){const start=sql.indexOf(`FUNCTION public.${rpc}(p_request jsonb)`),end=sql.indexOf('CREATE OR REPLACE FUNCTION',start+1),body=sql.slice(start,end<0?sql.length:end);assert.notEqual(start,-1);assert.match(body,/SECURITY DEFINER/);assert.match(body,/SET search_path=venture_private,pg_catalog/);assert.match(body,/PERFORM venture_private\.assert_member_binding_service_role\(\)/);assert.match(sql,new RegExp(`REVOKE ALL ON FUNCTION public\\.${rpc}\\(jsonb\\) FROM PUBLIC, anon, authenticated`));assert.match(sql,new RegExp(`GRANT EXECUTE ON FUNCTION public\\.${rpc}\\(jsonb\\) TO service_role`))}});
test('private state is RLS forced, exact matching is phone-led and no source facts are modified',()=>{const sql=read('012_member_binding_rpc_008_baseline.sql');for(const table of ['member_binding_match_tokens','member_binding_match_options','member_binding_candidates','member_binding_idempotency']){assert.match(sql,new RegExp(`ALTER TABLE venture_private\\.${table} FORCE ROW LEVEL SECURITY`));assert.match(sql,new RegExp(`REVOKE ALL ON venture_private\\.${table} FROM PUBLIC, anon, authenticated`))}assert.match(sql,/token_kind='phone'/);assert.match(sql,/candidate_row\.status<>'auto_eligible'/);assert.doesNotMatch(sql,/\b(?:UPDATE|INSERT|DELETE)\s+venture_private\.(?:crm_verifications|payment_evidence|membership_decisions|public_directory_profiles)/i);for(const forbidden of ['phone_number','raw_openid','raw_phone','contact_value'])assert.doesNotMatch(sql,new RegExp(forbidden,'i'))});
test('offline checker passes without database or network access',()=>{const output=childProcess.execFileSync(process.execPath,['scripts/cloudbase-member-binding-rpc-check.js'],{cwd:root,encoding:'utf8'});assert.match(output,/离线检查通过/);assert.match(output,/未执行 SQL/)});
