'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {REQUIRED_FUTURE_MIGRATION,RPC_NAME,DRAFT_CONTRACT,CloudBaseCrmMatchTokenTransportError,capabilityChecksum,verifyCrmMatchTokenCapabilityManifest,resolveCloudBaseCrmMatchTokenTransportConfig,safeRequest,PreparedCloudBaseCrmMatchTokenRepository}=require('../src/persistence/cloudbase-crm-match-token-transport');
const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
function manifest(){const value={version:'crm-match-token-rpc-v1',baseline:REQUIRED_FUTURE_MIGRATION,platform:'cloudbase_postgrest_rpc',rpc:RPC_NAME,evidence:{source:'cloudbase_readonly_contract_check',verifiedAt:'2026-08-12T00:00:00.000Z',rpcExistence:true,serviceRoleExecute:true,publicExecuteDenied:true,anonExecuteDenied:true,authenticatedExecuteDenied:true,separationOfDuties:true,idempotencyKeyUnique:true,tokenVersioning:true,safeResponseProjection:true}};value.checksum=capabilityChecksum(value);return value}
const request={userId:'member_fixture_1',tokenKind:'phone',generations:[{kind:'phone',keyVersion:'v2',tokenHash:hash('active')},{kind:'phone',keyVersion:'v1',tokenHash:hash('previous')}],source:'confirmed_crm_materialization',crmRecordVersionHash:hash('crm-record'),actorId:'operator_fixture_1',reviewerId:'reviewer_fixture_2',actorAuthorizationId:'authorization_execute_1',reviewAuthorizationId:'authorization_review_1',idempotencyKeyHash:hash('request'),writeScope:'member_binding_match_tokens_only'};
test('runtime transport is disabled and partial or explicit enablement fails closed',()=>{assert.equal(resolveCloudBaseCrmMatchTokenTransportConfig({}).enabled,false);assert.throws(()=>resolveCloudBaseCrmMatchTokenTransportConfig({CLOUDBASE_CRM_MATCH_TOKEN_TRANSPORT:'verified_postgrest_rpc'}),/拒绝保留/);assert.throws(()=>resolveCloudBaseCrmMatchTokenTransportConfig({CLOUDBASE_CRM_MATCH_TOKEN_WRITES_ENABLED:'true'}),/未应用 012/)});
test('deployed capability manifest would require exact RPC, 012 baseline and every readonly proof',()=>{const value=manifest();assert.equal(verifyCrmMatchTokenCapabilityManifest(value).checksum,value.checksum);for(const mutate of [item=>item.baseline='008_admin_session_rbac',item=>item.rpc='venture_arbitrary_write',item=>item.evidence.anonExecuteDenied=false,item=>item.evidence.separationOfDuties=false,item=>item.checksum='a'.repeat(64)]){const changed=manifest();mutate(changed);assert.throws(()=>verifyCrmMatchTokenCapabilityManifest(changed))}});
test('prepared repository sends one fixed RPC and only the redacted allowlisted projection',async()=>{const calls=[],repository=new PreparedCloudBaseCrmMatchTokenRepository({contract:DRAFT_CONTRACT,rpcInvoker:{kind:'mockable_verified_postgrest_rpc_invoker',runtimeEnabled:false,async call(name,payload){calls.push({name,payload});return {idempotencyStatus:'created',tokenGenerationCount:2,ignoredPrivate:'must-not-return'}}}}),result=await repository.replaceConfirmedPhoneTokens(request);assert.deepEqual(result,{idempotencyStatus:'created',tokenGenerationCount:2});assert.equal(calls[0].name,RPC_NAME);assert.deepEqual(calls[0].payload,{p_request:request});assert.equal(repository.safeReadiness().runtimeEnabled,false);assert.equal(repository.safeReadiness().directTableWrites,false);const serialized=JSON.stringify(calls);for(const forbidden of ['phoneNumber','rawPhone','recipient_phone','contact_match_token','payment','note'])assert.equal(serialized.includes(forbidden),false)});
test('unknown fields, duplicate generations, same actor, invalid response and upstream details are rejected',async()=>{assert.throws(()=>safeRequest({...request,rawPhone:'private'}),error=>error.code==='CLOUDBASE_CRM_MATCH_TOKEN_RPC_REQUEST_INVALID');assert.throws(()=>safeRequest({...request,reviewerId:request.actorId}),error=>error.code==='CLOUDBASE_CRM_MATCH_TOKEN_RPC_REQUEST_INVALID');assert.throws(()=>safeRequest({...request,generations:[request.generations[0],request.generations[0]]}),error=>error.code==='CLOUDBASE_CRM_MATCH_TOKEN_RPC_REQUEST_INVALID');let repository=new PreparedCloudBaseCrmMatchTokenRepository({rpcInvoker:{kind:'mockable_verified_postgrest_rpc_invoker',runtimeEnabled:false,async call(){throw new Error('raw CRM transport detail')}}});let error=await repository.replaceConfirmedPhoneTokens(request).catch(value=>value);assert.ok(error instanceof CloudBaseCrmMatchTokenTransportError);assert.doesNotMatch(JSON.stringify(error),/raw CRM/);repository=new PreparedCloudBaseCrmMatchTokenRepository({rpcInvoker:{kind:'mockable_verified_postgrest_rpc_invoker',runtimeEnabled:false,async call(){return {idempotencyStatus:'created',tokenGenerationCount:1}}}});await assert.rejects(()=>repository.replaceConfirmedPhoneTokens(request),failure=>failure.code==='CLOUDBASE_CRM_MATCH_TOKEN_RPC_INVALID_RESPONSE');assert.throws(()=>new PreparedCloudBaseCrmMatchTokenRepository({rpcInvoker:{kind:'mockable_verified_postgrest_rpc_invoker',runtimeEnabled:true,call(){}}}),/无网络 mock/)});
