'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {REQUIRED_FUTURE_MIGRATION,CrmMatchTokenProvisioningError,resolveCrmMatchTokenPreparationConfig,normalizePhone,VersionedCrmMatchTokenizer,OfflineCrmMatchTokenProvisioningService}=require('../src/persistence/crm-match-token-provisioning');
const key=byte=>Buffer.alloc(32,byte).toString('base64'),hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
const environment={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',DEMO_DATA_ONLY:'false',FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'false',CLOUDBASE_MEMBER_BINDING_WRITES_ENABLED:'false',CRM_MATCH_TOKEN_PROVISIONING_PREPARED:'true',CRM_MATCH_TOKEN_MIGRATION_APPLIED:REQUIRED_FUTURE_MIGRATION,CRM_MATCH_TOKEN_ACTIVE_KEY_VERSION:'v2',CRM_MATCH_TOKEN_ACTIVE_HMAC_KEY:key(2),CRM_MATCH_TOKEN_PREVIOUS_KEY_VERSION:'v1',CRM_MATCH_TOKEN_PREVIOUS_HMAC_KEY:key(1)};
function harness(overrides={}){const config=resolveCrmMatchTokenPreparationConfig({...environment,...overrides}),tokenizer=new VersionedCrmMatchTokenizer({config}),calls=[],repository={kind:'mockable_crm_match_token_repository',runtimeEnabled:false,replaceConfirmedPhoneTokens:async payload=>{calls.push(payload);return {idempotencyStatus:'created',tokenGenerationCount:payload.generations.length}}},service=new OfflineCrmMatchTokenProvisioningService({config,tokenizer,repository});return {config,tokenizer,calls,service}}
const request={actor:{verified:true,userId:'operator_fixture_1',permissions:['member_import.materialize.execute']},review:{approved:true,reviewerId:'reviewer_fixture_2',permission:'member_import.review',authorizationId:'authorization_fixture_1'},memberId:'member_fixture_1',phone:'138 0000-0000',crmRecordVersionHash:hash('crm-version'),idempotencyKey:hash('idempotency')};

test('preparation is off by default and rejects partial, demo, route or migration claims',()=>{const disabled=resolveCrmMatchTokenPreparationConfig({});assert.equal(disabled.prepared,false);assert.equal(disabled.runtimeEnabled,false);for(const input of [{CRM_MATCH_TOKEN_ACTIVE_KEY_VERSION:'v1'},{...environment,NODE_ENV:'test'},{...environment,DEMO_DATA_ONLY:'true'},{...environment,FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'true'},{...environment,CLOUDBASE_MEMBER_BINDING_WRITES_ENABLED:'true'},{...environment,CRM_MATCH_TOKEN_MIGRATION_APPLIED:'008_admin_session_rbac'}])assert.throws(()=>resolveCrmMatchTokenPreparationConfig(input));assert.throws(()=>resolveCrmMatchTokenPreparationConfig({...environment,CRM_MATCH_TOKEN_PREVIOUS_HMAC_KEY:''}),/成对/);assert.throws(()=>resolveCrmMatchTokenPreparationConfig({...environment,CRM_MATCH_TOKEN_PREVIOUS_KEY_VERSION:'v2'}),/必须不同/)});
test('phone normalization is strict and active/previous HMAC generations are domain separated',async()=>{const {tokenizer}=harness(),a=tokenizer.tokenizeForProvisioning('phone','+86 138-0000-0000'),b=tokenizer.tokenizeForProvisioning('phone','13800000000');assert.equal(normalizePhone('+86 (138) 0000 0000'),'13800000000');assert.equal(a.generations.length,2);assert.deepEqual(a,b);assert.notEqual(a.generations[0].tokenHash,a.generations[1].tokenHash);for(const item of a.generations){assert.match(item.tokenHash,/^[0-9a-f]{64}$/);assert.equal(item.tokenHash.includes('138'),false)}assert.equal(await tokenizer.tokenize('phone','13800000000'),a.generations[0].tokenHash);assert.throws(()=>normalizePhone('12345'),error=>error.code==='CRM_MATCH_TOKEN_PHONE_INVALID');assert.rejects(()=>tokenizer.tokenize('wechat_id','fixture'),error=>error.code==='CRM_MATCH_TOKEN_KIND_UNSUPPORTED')});
test('confirmed CRM provisioning sends only versioned hashes to an offline mock contract',async()=>{const {calls,service}=harness(),result=await service.provisionConfirmedCrmPhone(request);assert.equal(result.status,'prepared_contract_validated');assert.equal(result.runtimeEnabled,false);assert.equal(result.cloudWriteAttempted,false);assert.deepEqual(result.keyVersions,['v2','v1']);assert.equal(calls.length,1);assert.equal(calls[0].writeScope,'member_binding_match_tokens_only');assert.equal(calls[0].source,'confirmed_crm_materialization');assert.equal(calls[0].generations.length,2);const serialized=JSON.stringify({calls,result});for(const forbidden of ['13800000000','138 0000-0000','CRM_MATCH_TOKEN_ACTIVE_HMAC_KEY',key(1),key(2)])assert.equal(serialized.includes(forbidden),false);assert.equal(service.safeReadiness().routesEnabled,false);assert.equal(service.safeReadiness().memoryFallback,false)});
test('missing separation, permission, confirmation or repository success fails closed',async()=>{let {service}=harness();for(const patch of [{actor:{verified:false,userId:'operator_fixture_1',permissions:[]}},{review:{...request.review,reviewerId:'operator_fixture_1'}},{review:{...request.review,approved:false}},{phone:'not-a-phone'}])await assert.rejects(()=>service.provisionConfirmedCrmPhone({...request,...patch}),error=>error instanceof CrmMatchTokenProvisioningError);const config=resolveCrmMatchTokenPreparationConfig(environment),tokenizer=new VersionedCrmMatchTokenizer({config});assert.throws(()=>new OfflineCrmMatchTokenProvisioningService({config,tokenizer,repository:{kind:'mockable_crm_match_token_repository',runtimeEnabled:true,replaceConfirmedPhoneTokens(){}}}),/禁止真实写入/);service=new OfflineCrmMatchTokenProvisioningService({config,tokenizer,repository:{kind:'mockable_crm_match_token_repository',runtimeEnabled:false,async replaceConfirmedPhoneTokens(){throw new Error('raw phone storage failure')}}});const error=await service.provisionConfirmedCrmPhone(request).catch(value=>value);assert.equal(error.code,'CRM_MATCH_TOKEN_PROVISIONING_UNAVAILABLE');assert.doesNotMatch(JSON.stringify(error),/raw phone|138/)});
