'use strict';

const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {resolveWechatIdentityConfig}=require('../src/auth/wechat-config');
const {FormalFirstBindingService}=require('../src/auth/first-binding-service');
const {MEMBER_BINDING_OPERATIONS,StagedMemberBindingRepository}=require('../src/persistence/member-binding-repository');
const key=value=>Buffer.alloc(32,value).toString('base64');
const config=resolveWechatIdentityConfig({NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',WECHAT_LOGIN_ENABLED:'true',MEMBER_IDENTITY_PROVIDER:'external_verified_session',MEMBER_BINDING_MODE:'crm_exact_match_or_operator_review',MEMBER_SESSION_REVOCATION_STORE:'external_persistent',WECHAT_MINIPROGRAM_APP_ID:'wx1234567890abcdef',WECHAT_MINIPROGRAM_APP_SECRET:'fixture-secret',WECHAT_IDENTITY_SUBJECT_HMAC_KEY:key(1),MEMBER_SESSION_ENCRYPTION_KEY:key(2),MEMBER_SESSION_ISSUER:'fixture-issuer',MEMBER_SESSION_AUDIENCE:'fixture-audience'});
const digest=value=>crypto.createHash('sha256').update(value).digest('hex');

function harness({adapterFailure=false,phoneFailure=false,stageResult}={}){
  const calls=[];
  const adapter={execute:async(operation,payload)=>{
    calls.push(['repository',operation,payload]);
    if(adapterFailure)throw new Error('raw database row');
    if(operation===MEMBER_BINDING_OPERATIONS.STAGE_CANDIDATE)return stageResult||{id:'binding_candidate_1',candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:true,groupStatus:'in_group',membershipMonthEffective:true,dataComplete:true,contradiction:false,riskFlags:[],entitlementProjectionReady:true}};
    if(operation===MEMBER_BINDING_OPERATIONS.LIST_PENDING)return [{id:'binding_candidate_1',status:'operator_review_required',review_reasons:['ambiguous_match'],evidence_types:['openid_verified','phone_user_consent'],candidate_count:1,conflict_status:'unique_candidate',created_at:'2026-08-11T00:00:00.000Z',phone:'never-return'}];
    if(operation===MEMBER_BINDING_OPERATIONS.CONFIRM_AND_REEVALUATE)return {bindingStatus:payload.confirmationMode==='automatic_exact_match'?'auto_confirmed':'operator_confirmed',entitlementReevaluated:true,entitlementActive:true};
    return {status:'rejected'};
  }};
  const repository=new StagedMemberBindingRepository({adapter});
  const service=new FormalFirstBindingService({identityConfig:config,exchangeClient:{exchange:async()=>({subjectType:'openid',subject:'raw-openid-fixture'})},phoneGrantVerifier:{verify:async code=>{calls.push(['phone',code]);if(phoneFailure)throw new Error('raw phone upstream');return {verified:true,phoneNumber:'13800000000'}}},matchTokenizer:{tokenize:async(kind,value)=>{calls.push(['tokenize',kind,value]);return digest(`fixture:${kind}:${value}`)}},adminSessionService:{authorizeAction:async input=>{calls.push(['admin',input.permission,input.idempotencyKey]);return {userId:'operator_fixture_1',authorizationId:'authorization_fixture_1'}}},repository});
  return {calls,repository,service};
}

test('verified phone plus one active effective in-group CRM match auto-binds and re-evaluates access',async()=>{const {calls,service}=harness();const result=await service.start({code:'fixture_code_1',phoneGrantCode:'phone_consent_code',wechatId:'用户主动填写微信号',groupNickname:'用户主动填写群昵称'});assert.equal(result.status,'bound_active');assert.equal(result.automaticMemberBinding,true);assert.equal(result.automaticMembershipActivation,false);assert.equal(result.entitlementReevaluated,true);assert.equal(result.accessUnlocked,true);assert.equal(result.sessionIssued,false);const stage=calls.find(item=>item[1]===MEMBER_BINDING_OPERATIONS.STAGE_CANDIDATE),serialized=JSON.stringify(stage);for(const raw of ['raw-openid-fixture','13800000000','用户主动填写微信号','用户主动填写群昵称','phone_consent_code'])assert.equal(serialized.includes(raw),false);for(const value of Object.values(stage[2].matchTokens))assert.match(value,/^[0-9a-f]{64}$/);const bind=calls.find(item=>item[1]===MEMBER_BINDING_OPERATIONS.CONFIRM_AND_REEVALUATE);assert.equal(bind[2].selectedMatchId,'match_candidate_1');assert.equal('memberId' in bind[2],false);assert.equal(bind[2].writeScope,'identity_binding_only');assert.equal(bind[2].confirmationMode,'automatic_exact_match')});
test('no match, ambiguity, invalid group/month/account, missing CRM or risk flags go to operator review',async()=>{const cases=[
  [{id:'binding_candidate_1',candidateCount:0,conflictStatus:'no_match',crmAccessProjection:{}},'no_match'],
  [{id:'binding_candidate_1',candidateCount:2,conflictStatus:'multiple_candidates',crmAccessProjection:{}},'ambiguous_or_conflicting_match'],
  [{id:'binding_candidate_1',candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:false,groupStatus:'in_group',membershipMonthEffective:true,dataComplete:true,contradiction:false,riskFlags:[],entitlementProjectionReady:true}},'account_not_active'],
  [{id:'binding_candidate_1',candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:true,groupStatus:'left_group',membershipMonthEffective:true,dataComplete:true,contradiction:false,riskFlags:[],entitlementProjectionReady:true}},'group_not_active'],
  [{id:'binding_candidate_1',candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:true,groupStatus:'in_group',membershipMonthEffective:false,dataComplete:true,contradiction:false,riskFlags:[],entitlementProjectionReady:true}},'membership_month_not_effective'],
  [{id:'binding_candidate_1',candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:true,groupStatus:'in_group',membershipMonthEffective:true,dataComplete:false,contradiction:true,riskFlags:['conflict'],entitlementProjectionReady:true}},'crm_missing_or_contradictory']
];for(const [stageResult,reason] of cases){const {calls,service}=harness({stageResult}),result=await service.start({code:'fixture_code_1',phoneGrantCode:'phone_consent_code'});assert.equal(result.status,'operator_review_required');assert.equal(result.reviewReasons.includes(reason),true);assert.equal(result.automaticMemberBinding,false);assert.equal(calls.some(call=>call[1]===MEMBER_BINDING_OPERATIONS.CONFIRM_AND_REEVALUATE),false)}});
test('missing phone consent never auto-binds and supplied phone grant must verify server-side',async()=>{let harnessed=harness();let result=await harnessed.service.start({code:'fixture_code_1'});assert.equal(result.status,'operator_review_required');assert.equal(result.reviewReasons.includes('verified_phone_required'),true);assert.equal(harnessed.calls.some(call=>call[0]==='phone'),false);assert.equal(harnessed.calls.some(call=>call[1]===MEMBER_BINDING_OPERATIONS.CONFIRM_AND_REEVALUATE),false);harnessed=harness({phoneFailure:true});await assert.rejects(()=>harnessed.service.start({code:'fixture_code_1',phoneGrantCode:'phone_consent_code'}),error=>error.code==='MEMBER_BINDING_UNAVAILABLE'&&!error.message.includes('upstream'));assert.equal(harnessed.calls.some(call=>call[0]==='repository'),false)});
test('008 authorization precedes manual review and client never submits an internal member id',async()=>{const {calls,service}=harness();let result=await service.listPending({request:{},limit:10,idempotencyKey:'binding-list-1'});assert.equal(result.items[0].rawValuesReturned,false);assert.equal(JSON.stringify(result).includes('never-return'),false);assert.deepEqual(calls.slice(0,2).map(call=>call[0]),['admin','repository']);calls.length=0;result=await service.confirm({request:{},candidateId:'binding_candidate_1',selectedMatchId:'match_candidate_1',reasonCode:'crm_unique_match',idempotencyKey:'binding-confirm-1'});assert.equal(result.bindingStatus,'operator_confirmed');assert.equal(result.entitlementReevaluated,true);assert.equal(result.automaticMembershipActivation,false);assert.equal(result.sessionIssued,false);assert.equal(result.crmChanged,false);assert.deepEqual(calls.slice(0,2).map(call=>call[0]),['admin','repository']);assert.equal(calls[0][1],'membership.recompute');assert.equal(calls[1][2].writeScope,'identity_binding_only');assert.equal('memberId' in calls[1][2],false);calls.length=0;result=await service.reject({request:{},candidateId:'binding_candidate_1',reasonCode:'no_safe_match',idempotencyKey:'binding-reject-1'});assert.equal(result.bindingCreated,false);assert.equal(result.membershipChanged,false);assert.deepEqual(calls.slice(0,2).map(call=>call[0]),['admin','repository'])});
test('invalid reasons and repository failures fail closed with no CRM or memory fallback',async()=>{let harnessed=harness();await assert.rejects(()=>harnessed.service.confirm({request:{},candidateId:'binding_candidate_1',selectedMatchId:'match_candidate_1',reasonCode:'amount_auto_match',idempotencyKey:'binding-confirm-2'}),error=>error.code==='MEMBER_BINDING_INPUT_INVALID');assert.equal(harnessed.calls.length,0);harnessed=harness({adapterFailure:true});await assert.rejects(()=>harnessed.service.start({code:'fixture_code_1'}),error=>error.code==='MEMBER_BINDING_REPOSITORY_UNAVAILABLE'&&!error.message.includes('database'));const readiness=harnessed.repository.safeReadiness();assert.equal(readiness.crmWrites,false);assert.equal(readiness.memoryFallback,false);assert.equal(readiness.activated,false);await assert.rejects(()=>harnessed.repository.execute('crm.write',{}),/白名单/)});
