'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {ROLE_PERMISSIONS,permissionsForRoles}=require('../src/auth/admin-rbac');
const {resolveFormalAdminAuthConfig}=require('../src/auth/admin-auth-config');
const {FormalAdminSessionService}=require('../src/auth/admin-session-service');
const key=Buffer.alloc(32,7).toString('base64');
const production={FORMAL_ADMIN_AUTH_ENABLED:'true',NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_MIGRATIONS_APPLIED:'008_admin_session_rbac',ADMIN_AUTH_MODE:'external_session',ADMIN_IDENTITY_PROVIDER:'external_verified',ADMIN_SESSION_STORE:'cloudbase_pg',ADMIN_SESSION_HASH_KEY:key,ADMIN_SUBJECT_HMAC_KEY:Buffer.alloc(32,8).toString('base64'),ADMIN_SESSION_ISSUER:'venture-admin'};
const now=new Date('2026-08-05T08:00:00.000Z');

test('four fixed roles are least privilege and auditor has no write permission',()=>{assert.deepEqual(Object.keys(ROLE_PERMISSIONS),['system_admin','operations','reviewer','auditor']);assert.equal(ROLE_PERMISSIONS.auditor.some(code=>!code.endsWith('.read')),false);assert.equal(ROLE_PERMISSIONS.operations.includes('member_import.review'),false);assert.equal(ROLE_PERMISSIONS.reviewer.includes('member_import.materialize.execute'),false);assert.throws(()=>permissionsForRoles(['client_supplied_admin']),/白名单/)});
test('formal auth is disabled by default and staging or partial config fails closed',()=>{assert.equal(resolveFormalAdminAuthConfig({}).enabled,false);assert.throws(()=>resolveFormalAdminAuthConfig({ADMIN_SESSION_HASH_KEY:key}),/未启用/);assert.throws(()=>resolveFormalAdminAuthConfig({...production,DEPLOYMENT_PROFILE:'cloudbase_staging_demo',DEMO_DATA_ONLY:'true'}),/staging/);assert.equal(resolveFormalAdminAuthConfig(production).safeSummary.credentialsExposed,false)});

function harness(overrides={}){const calls=[],config=resolveFormalAdminAuthConfig(production),session={session_id:'session-fixture',user_id:'admin-fixture',status:'active',issued_at:now.toISOString(),expires_at:'2026-08-05T09:00:00.000Z',authenticated_at:now.toISOString(),step_up_verified_at:now.toISOString(),roles:['reviewer'],permissions:['member_import.review','member_import.materialize.request']};const repository={beginSession:async input=>{calls.push(['begin',input]);return {session_id:'session-fixture',status:'active'}},resolveSession:async input=>{calls.push(['resolve',input]);return session},reserveAction:async input=>{calls.push(['reserve',input]);return {authorized:true,authorization_id:'authorization-fixture'}}};const service=new FormalAdminSessionService({config,identityVerifier:{verify:async()=>({verified:true,provider:'corporate_sso',subject:'synthetic-subject',authenticatedAt:now.toISOString(),stepUpVerified:true})},repository,clock:()=>now,randomBytes:()=>Buffer.alloc(32,9),...overrides});return {service,calls,repository,session}}

test('login returns an opaque bearer without roles and stores only hashes',async()=>{const {service,calls}=harness(),result=await service.login('synthetic-assertion');assert.equal(result.rolesNotEmbedded,true);assert.equal(Object.hasOwn(result,'roles'),false);assert.match(result.accessToken,/^[A-Za-z0-9_-]{43}$/);const serialized=JSON.stringify(calls);assert.equal(serialized.includes('synthetic-subject'),false);assert.equal(serialized.includes(result.accessToken),false);assert.match(calls[0][1].subjectHash,/^[0-9a-f]{64}$/);assert.match(calls[0][1].sessionHash,/^[0-9a-f]{64}$/)});
test('formal request rejects cookies, demo identities and client role claims',async()=>{const {service}=harness();for(const headers of [{cookie:'admin=x'},{'x-demo-user':'x'},{'x-admin-role':'system_admin'}])await assert.rejects(()=>service.resolveRequest({headers}),error=>error.code==='ADMIN_AUTHENTICATION_REQUIRED')});
test('each request re-resolves server permissions and revoked or failed stores fail closed',async()=>{const {service,calls,session}=harness(),authorization='Bearer '+Buffer.alloc(32,9).toString('base64url');await service.resolveRequest({headers:{authorization}});await service.resolveRequest({headers:{authorization}});assert.equal(calls.filter(call=>call[0]==='resolve').length,2);session.status='revoked';await assert.rejects(()=>service.resolveRequest({headers:{authorization}}),error=>error.code==='ADMIN_AUTHENTICATION_REQUIRED');const unavailable=harness({repository:{resolveSession:async()=>{throw new Error('fixture')}}}).service;await assert.rejects(()=>unavailable.resolveRequest({headers:{authorization}}),error=>error.code==='ADMIN_AUTH_UNAVAILABLE')});
test('high-risk authorization requires step-up, idempotency and separation before repository mutation',async()=>{const {service,calls,session}=harness(),request={headers:{authorization:'Bearer '+Buffer.alloc(32,9).toString('base64url')}};await assert.rejects(()=>service.authorizeAction({request,permission:'member_import.materialize.request',idempotencyKey:'short'}),error=>error.code==='ADMIN_IDEMPOTENCY_REQUIRED');await assert.rejects(()=>service.authorizeAction({request,permission:'member_import.materialize.request',idempotencyKey:'fixture-action-1',excludedActorIds:['admin-fixture']}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED');assert.equal(calls.some(call=>call[0]==='reserve'),false);session.step_up_verified_at='2026-08-05T07:00:00.000Z';await assert.rejects(()=>service.authorizeAction({request,permission:'member_import.materialize.request',idempotencyKey:'fixture-action-2'}),error=>error.code==='ADMIN_STEP_UP_REQUIRED');session.step_up_verified_at=now.toISOString();const result=await service.authorizeAction({request,permission:'member_import.materialize.request',idempotencyKey:'fixture-action-3'});assert.equal(result.authorizationId,'authorization-fixture');assert.equal(calls.filter(call=>call[0]==='reserve').length,1)});
test('008 migration exposes no client grants and preserves hashed identities',()=>{const sql=fs.readFileSync(path.join(__dirname,'../db/migrations/008_admin_session_rbac.sql'),'utf8');for(const term of ['external_admin_identity_bindings','subject_hash','admin_sessions','session_hash','admin_action_authorizations','FORCE ROW LEVEL SECURITY','assert_cloudbase_service_role','p_excluded_actor_ids'])assert.match(sql,new RegExp(term));assert.doesNotMatch(sql,/GRANT (?:SELECT|EXECUTE)[\s\S]{0,180} TO (?:anon|authenticated)/i);assert.doesNotMatch(sql,/raw_subject|phone|contact_value/i)});
