'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {GovernedImportProtector}=require('../src/persistence/governed-import-service');
const {resolveGovernedMaterializationConfig}=require('../src/persistence/governed-materialization-config');
const {CloudBaseMaterializationRepository,MaterializationUnavailableError}=require('../src/persistence/governed-materialization-repository');
const {GovernedMaterializationService,buildFactPayload}=require('../src/persistence/governed-materialization-service');
const key=Buffer.alloc(32,11).toString('base64'),matchKey=Buffer.alloc(32,12).toString('base64');
const production={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_MIGRATIONS_APPLIED:'007_governed_materialization',GOVERNED_MATERIALIZATION_ENABLED:'true',GOVERNED_MATERIALIZATION_ADMIN_PROVIDER:'external_verified_session',GOVERNED_MATERIALIZATION_AUDIT_STORE:'cloudbase_pg',GOVERNED_MATERIALIZATION_IDEMPOTENCY_STORE:'cloudbase_pg'};
function source(protector,domain='crm'){const batch='batch-fixture',row='row-fixture',protectedData=domain==='crm'?{evidence_note:'匿名核验备注'}:domain==='payment'?{recipient_phone:'synthetic-contact',collected_cents:'10000',refund_cents:'0',payment_at:'2026-07-01T00:00:00Z',product_name:'匿名会籍产品'}:{member_reference:'REF-FIXTURE'};const safe=domain==='crm'?{crm_verification_status:'verified',membership_start:'2026-01-01',membership_end:'2027-01-01',group_status:'in_group'}:domain==='payment'?{evidenceCandidate:true,productRuleStatus:'matched'}:{public_display_consent:'yes',eligibleForReview:true,contact_mode:'request_only',public_display_name:'匿名成员',organization:'示例机构',industry:'科技',interests:'研究',investment_stage:'成长期',city:'示例城',expertise:'分析',bio:'匿名简介'};return {row_id:row,batch_id:batch,domain,row_fingerprint:'a'.repeat(64),row_status:'matched',match_status:'matched',matched_user_id:'member-fixture',row_reviewed_by:'reviewer-fixture',batch_actor_id:'importer-fixture',validation_codes:[],safe_projection:safe,protected_payload_ciphertext:protector.protect(protectedData,`${batch}:${row}:${domain}`)}}

test('materialization config is explicit, latest-migration-only and fail closed',()=>{assert.equal(resolveGovernedMaterializationConfig({}).enabled,false);assert.throws(()=>resolveGovernedMaterializationConfig({...production,DEMO_DATA_ONLY:'true'}),/匿名 staging/);assert.throws(()=>resolveGovernedMaterializationConfig({...production,CLOUDBASE_PG_MIGRATIONS_APPLIED:'006_governed_member_import'}),/007_governed_materialization/);const config=resolveGovernedMaterializationConfig(production);assert.equal(config.safeSummary.separationOfDuties,true);assert.equal(config.safeSummary.memoryFallback,false)});

test('request decrypts only server-side and sends an allowlisted encrypted CRM fact',async()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:matchKey}),calls=[],repository={kind:'cloudbase_gateway',getSource:async()=>source(protector),request:async input=>{calls.push(input);return {request_id:input.requestId}}};const service=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'requester-fixture',permissions:['member_import.materialize.request']}),uuid:()=> '00000000-0000-4000-8000-000000000001'});const result=await service.requestMaterialization({rowId:'row-fixture',idempotencyKey:'fixture-materialize-1'});assert.equal(result.sensitiveValuesReturned,false);assert.equal(result.status,'awaiting_independent_executor');const serialized=JSON.stringify(calls[0]);assert.equal(serialized.includes('匿名核验备注'),false);assert.deepEqual(Object.keys(calls[0].factPayload).sort(),['evidence_note_ciphertext','fact_id','group_status','membership_end','membership_start','user_id','verification_status'].sort())});

test('importer or match reviewer cannot request, and requester cannot execute',async()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:matchKey}),repository={kind:'cloudbase_gateway',getSource:async()=>source(protector),request:async()=>{throw new Error('must not call')},getRequest:async()=>({status:'approved_for_execution',requester_id:'requester-fixture',batch_actor_id:'importer-fixture',row_reviewed_by:'reviewer-fixture',domain:'crm'}),execute:async()=>{throw new Error('must not call')}};const requester=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'reviewer-fixture',permissions:['member_import.materialize.request']})});await assert.rejects(()=>requester.requestMaterialization({rowId:'row-fixture',idempotencyKey:'fixture-materialize-2'}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED');const executor=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'requester-fixture',permissions:['member_import.materialize.execute']})});await assert.rejects(()=>executor.executeMaterialization({requestId:'request-fixture'}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED')});

test('rows with validation errors cannot materialize and compensation needs an independent actor',async()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:matchKey}),invalid={...source(protector),validation_codes:['validation_fixture']},request={status:'applied',executor_id:'executor-fixture',domain:'crm'};let compensated=false;const repository={kind:'cloudbase_gateway',getSource:async()=>invalid,request:async()=>{throw new Error('must not call')},getRequest:async()=>request,compensate:async()=>{compensated=true;return {status:'compensated'}}};const blocked=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'requester-fixture',permissions:['member_import.materialize.request']})});await assert.rejects(()=>blocked.requestMaterialization({rowId:'row-fixture',idempotencyKey:'fixture-materialize-3'}),error=>error.code==='ROW_NOT_MATERIALIZABLE');const sameExecutor=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'executor-fixture',permissions:['member_import.materialize.compensate']})});await assert.rejects(()=>sameExecutor.compensate({requestId:'request-fixture',codes:['operator_error']}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED');const independent=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'compensator-fixture',permissions:['member_import.materialize.compensate']})});assert.deepEqual(await independent.compensate({requestId:'request-fixture',codes:['operator_error']}),{status:'compensated'});assert.equal(compensated,true)});

test('payment refunds remain needs-review and an order never directly activates membership',()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:matchKey}),input=source(protector,'payment'),payload=buildFactPayload(input,{collected_cents:'10000',refund_cents:'5000',payment_at:'2026-07-01T00:00:00Z',product_name:'匿名产品'},{factId:'payment-fixture',protector});assert.equal(payload.refund_status,'partial');assert.equal(payload.evidence_status,'needs_review');assert.equal('membership_status' in payload,false);assert.equal('final_status' in payload,false)});

test('directory materializes hidden and requires a fourth independent approval',async()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:matchKey}),directory=source(protector,'directory'),payload=buildFactPayload(directory,{member_reference:'REF-FIXTURE'},{factId:'directory-fixture',protector});assert.equal(payload.contact_mode,'request_only');for(const forbidden of ['phone','wechat','recipient_phone','contact_value'])assert.equal(JSON.stringify(payload).includes(forbidden),false);let approved=false;const request={request_id:'request-fixture',domain:'directory',status:'applied',fact_status:'hidden_pending_publication',requester_id:'requester-fixture',executor_id:'executor-fixture',batch_actor_id:'importer-fixture',row_reviewed_by:'reviewer-fixture'};const repository={kind:'cloudbase_gateway',getSource:async()=>directory,getRequest:async()=>request,approveDirectory:async()=>{approved=true;return {status:'published'}}};const denied=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'executor-fixture',permissions:['directory.publish.approve']})});await assert.rejects(()=>denied.approveDirectoryPublication({requestId:'request-fixture'}),error=>error.code==='SEPARATION_OF_DUTIES_REQUIRED');const allowed=new GovernedMaterializationService({repository,protector,adminResolver:async()=>({verified:true,userId:'directory-approver',permissions:['directory.publish.approve']})});assert.deepEqual(await allowed.approveDirectoryPublication({requestId:'request-fixture'}),{status:'published'});assert.equal(approved,true)});

test('gateway failure is generic 503 and fixed RPC path never reflects upstream body',async()=>{const config={enabled:true,mode:'cloudbase_gateway',runtimeEnvironment:'production',origin:'https://fixture.api.tcloudbasegateway.com',serverApiKey:'fixture-only',timeoutMs:1000,maxResponseBytes:4096};let url;const repository=new CloudBaseMaterializationRepository({config,fetchImpl:async target=>{url=String(target);return {ok:false,status:500,headers:{get:()=>null},text:async()=>'{"private":"never reflect"}'}}});await assert.rejects(()=>repository.execute({requestId:'request-fixture',executorId:'executor-fixture'}),error=>error instanceof MaterializationUnavailableError&&error.statusCode===503&&!error.message.includes('private'));assert.match(url,/\/rpc\/venture_execute_materialization$/)});
