'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {previewCrmVerificationCsv}=require('../src/imports');
const {resolveGovernedImportConfig}=require('../src/persistence/governed-import-config');
const {CloudBaseGovernedImportRepository,GovernedImportUnavailableError}=require('../src/persistence/governed-import-repository');
const {GovernedImportProtector,GovernedImportService,decideMembershipProjection}=require('../src/persistence/governed-import-service');

const key=Buffer.alloc(32,7).toString('base64');
const production={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_MIGRATIONS_APPLIED:'006_governed_member_import',GOVERNED_MEMBER_IMPORTS_ENABLED:'true',GOVERNED_IMPORT_ADMIN_PROVIDER:'external_verified_session',GOVERNED_IMPORT_AUDIT_STORE:'cloudbase_pg',GOVERNED_IMPORT_IDEMPOTENCY_STORE:'cloudbase_pg',GOVERNED_IMPORT_ENCRYPTION_KEY:key,MEMBER_MATCH_HMAC_KEY:Buffer.alloc(32,8).toString('base64')};
const crmHeader='internal_member_ref,contact_match_token,crm_verification_status,membership_start,membership_end,group_status,evidence_note,migration_status';

test('governed import config is explicit, production-only and never falls back to memory',()=>{assert.equal(resolveGovernedImportConfig({}).enabled,false);assert.throws(()=>resolveGovernedImportConfig({...production,DEMO_DATA_ONLY:'true'}),/匿名 staging/);assert.throws(()=>resolveGovernedImportConfig({...production,GOVERNED_IMPORT_ENCRYPTION_KEY:''}),/配置不完整/);const config=resolveGovernedImportConfig(production);assert.equal(config.safeSummary.memoryFallback,false);assert.equal(JSON.stringify(config.safeSummary).includes(key),false)});

test('CRM CSV keeps matching values and notes out of the safe projection',()=>{const result=previewCrmVerificationCsv(`${crmHeader}\nREF-DEMO,synthetic-contact,verified,2026-01-01,2027-01-01,in_group,仅测试备注,ready`).results[0];assert.equal(result.valid,true);for(const field of ['internal_member_ref','contact_match_token','evidence_note'])assert.equal(field in result.normalized,false);assert.equal(result.normalized.determinesMembershipAlone,false);const unsafe=previewCrmVerificationCsv(`${crmHeader}\nREF-DEMO,synthetic-contact,verified,2026-01-01,2027-01-01,in_group,=IMPORT(),ready`).results[0];assert.match(unsafe.errors.join(' '),/CSV 公式/)});

test('protected row encryption is bound to its batch and row context',()=>{const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:Buffer.alloc(32,8).toString('base64')}),ciphertext=protector.protect({contact:'fixture'},'batch:row:crm');assert.deepEqual(protector.unprotect(ciphertext,'batch:row:crm'),{contact:'fixture'});assert.throws(()=>protector.unprotect(ciphertext,'batch:other:crm'))});

test('persistent staging verifies admin first, encrypts protected cells and returns no sensitive values',async()=>{const calls=[];let sequence=0;const repository={kind:'cloudbase_gateway',beginBatch:async input=>calls.push(['begin',input]),stageRows:async input=>calls.push(['stage',input])};const service=new GovernedImportService({repository,protector:new GovernedImportProtector({encryptionKey:key,matchHmacKey:Buffer.alloc(32,8).toString('base64')}),adminResolver:async()=>({verified:true,userId:'admin-fixture',permissions:['member_import.stage']}),uuid:()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`});const result=await service.stageCsv({adminSession:'opaque',domain:'crm',csv:`${crmHeader}\nREF-DEMO,synthetic-contact,verified,2026-01-01,2027-01-01,in_group,仅测试备注,ready`,idempotencyKey:'fixture-idempotency-1'});assert.equal(result.persistent,true);assert.equal(result.sensitiveValuesReturned,false);const serialized=JSON.stringify(calls[1]);for(const secret of ['synthetic-contact','仅测试备注','REF-DEMO'])assert.equal(serialized.includes(secret),false);assert.match(calls[1][1].rows[0].match_key_hash,/^[0-9a-f]{64}$/);assert.notEqual(calls[1][1].rows[0].protected_payload_ciphertext.length,0)});

test('missing verified admin and repository errors fail closed before any false success',async()=>{let touched=false;const repository={kind:'cloudbase_gateway',beginBatch:async()=>{touched=true},stageRows:async()=>{throw new GovernedImportUnavailableError()}};const protector=new GovernedImportProtector({encryptionKey:key,matchHmacKey:Buffer.alloc(32,8).toString('base64')});const denied=new GovernedImportService({repository,protector,adminResolver:async()=>null});await assert.rejects(()=>denied.stageCsv({domain:'crm',csv:`${crmHeader}\nREF,X,verified,2026-01-01,2027-01-01,in_group,,ready`,idempotencyKey:'fixture-idempotency-2'}),error=>error.code==='VERIFIED_ADMIN_REQUIRED');assert.equal(touched,false);const failing=new GovernedImportService({repository,protector,adminResolver:async()=>({verified:true,userId:'admin-fixture',permissions:['member_import.stage']})});await assert.rejects(()=>failing.stageCsv({domain:'crm',csv:`${crmHeader}\nREF,X,verified,2026-01-01,2027-01-01,in_group,,ready`,idempotencyKey:'fixture-idempotency-3'}),error=>error.code==='GOVERNED_IMPORT_UNAVAILABLE')});

test('membership activation requires every minimal fact and explicit human approval',()=>{const good={account_active:true,window_current:true,crm_verified:true,group_status:'in_group',payment_verified:true,payment_reviewed_at:'2026-07-01T00:00:00Z',refund_status:'none',conflict_present:false,recompute_required:true};assert.deepEqual(decideMembershipProjection(good,{manualApproved:true}),{finalStatus:'active',reasonCodes:[]});const refund=decideMembershipProjection({...good,refund_status:'partial'},{manualApproved:true});assert.equal(refund.finalStatus,'needs_review');assert.ok(refund.reasonCodes.includes('refund_requires_review'));assert.ok(decideMembershipProjection(good).reasonCodes.includes('manual_approval_required'));assert.ok(decideMembershipProjection({...good,group_status:'unknown'},{manualApproved:true}).reasonCodes.includes('group_unknown'))});

test('gateway repository uses fixed RPC/view paths and hides upstream failures',async()=>{
  const config={enabled:true,mode:'cloudbase_gateway',runtimeEnvironment:'production',origin:'https://fixture.api.tcloudbasegateway.com',serverApiKey:'fixture-only',timeoutMs:1000,maxResponseBytes:4096};
  const calls=[];
  const repository=new CloudBaseGovernedImportRepository({config,fetchImpl:async(url,options)=>{calls.push({url:String(url),options});return {ok:true,status:200,headers:{get:name=>name==='content-type'?'application/json':null},text:async()=>'{"status":"staging"}'}}});
  await repository.beginBatch({batchId:'batch-fixture',domain:'crm',actorId:'admin-fixture',idempotencyKeyHash:'a'.repeat(64),csvSha256:'b'.repeat(64),totalRows:1});
  assert.match(calls[0].url,/\/rpc\/venture_begin_governed_import$/);assert.equal(calls[0].options.redirect,'error');
  const denied=new CloudBaseGovernedImportRepository({config,fetchImpl:async()=>({ok:false,status:403,headers:{get:()=>null},text:async()=>'{"secret":"never reflect"}'})});
  await assert.rejects(()=>denied.beginBatch({batchId:'batch-fixture',domain:'crm',actorId:'admin-fixture',idempotencyKeyHash:'a'.repeat(64),csvSha256:'b'.repeat(64),totalRows:1}),error=>error.code==='GOVERNED_IMPORT_UNAVAILABLE'&&!error.message.includes('secret'));
});
