'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {PassThrough}=require('node:stream');
const server=require('../src/server'),store=require('../src/store');
const {MEMBERSHIP_TIERS,MEMBERSHIP_TIER_REASON_CODES,membershipTierCandidateForPrice,confirmedMembershipTier}=require('../src/membership-tiers');
const {previewPaymentClueCsv}=require('../src/payment-clue-import');
const {evaluateMembership}=require('../src/domain');

const call=(path,{user='active',role,method='GET',body,headers={}}={})=>new Promise((resolve,reject)=>{const req=new PassThrough();req.method=method;req.url=path;req.headers={host:'localhost','x-demo-user':user,...(role?{'x-demo-role':role}:{}),...(body?{'content-type':'application/json'}:{}),...headers};const response={statusCode:200,headers:{},writeHead(status,h){this.statusCode=status;this.headers=h||{}},end(chunk=''){const text=String(chunk||'');resolve({status:this.statusCode,payload:text?JSON.parse(text):{}})}};req.on('error',reject);server.emit('request',req,response);req.end(body?JSON.stringify(body):'')});

test('four maintained tiers have the exact standard prices',()=>{assert.deepEqual(MEMBERSHIP_TIERS.map(x=>[x.key,x.label,x.standardPriceCents]),[['angel_shareholder','天使轮股东',20000],['a1_shareholder','A1 轮股东',66600],['a2_shareholder','A2 轮股东',79900],['honorary_director','荣誉董事',49900]]);for(const cents of [20000,66600,79900,49900])assert.ok(membershipTierCandidateForPrice(cents));assert.equal(membershipTierCandidateForPrice(49900).tierKey,'honorary_director')});

test('all three payment sources use standard prices and 499 becomes an honorary director candidate',()=>{for(const source of ['wechat_shop_order','wechat_merchant_receipt','manual_transfer']){const headers=source==='wechat_shop_order'?'收件人姓名,订单发货时间,收件人手机号,商品价格(单件)':source==='wechat_merchant_receipt'?'付款人姓名,支付时间,付款人手机号,支付金额':'成员姓名,转账时间,手机号,转账金额';const rows=['匿名甲,2026-08-01,13800008000,200','匿名乙,2026-08-01,13800008000,666','匿名丙,2026-08-01,13800008000,799','匿名丁,2026-08-01,13800008000,499'];const result=previewPaymentClueCsv(`${headers}\n${rows.join('\n')}`,{source});assert.equal(result.counts.angelCandidateRows,1,source);assert.equal(result.counts.a1CandidateRows,1,source);assert.equal(result.counts.a2CandidateRows,1,source);assert.equal(result.counts.honoraryDirectorRenewalCandidateRows,1,source);assert.equal(result.counts.priceUnclassifiedRows,0,source);assert.equal(result.counts.needsManualRows,0,source);assert.equal(result.safeguards.determinesMembershipAlone,false)}});

test('operator can assign honorary director with an internal reason while group remains the final gate',async()=>{const user=store.users.active_private,before={membershipTier:user.membershipTier,membershipTierReasonCode:user.membershipTierReasonCode,honoraryDirectorStatus:user.honoraryDirectorStatus,honoraryDirectorReasonCode:user.honoraryDirectorReasonCode,groupStatus:user.groupStatus};try{const response=await call(`/api/admin/members/${user.id}/group-status`,{role:'administrator',method:'PATCH',body:{groupStatus:'left',renewalNoticeStatus:'not_notified',membershipTier:'honorary_director',membershipTierReasonCode:'invited',honoraryDirectorStatus:'confirmed'},headers:{'x-admin-confirmation':'membership.group_status','idempotency-key':'membership-tier-honorary-fixture'}});assert.equal(response.status,200);assert.equal(response.payload.membershipTierLabel,'荣誉董事');assert.equal(confirmedMembershipTier(user).label,'荣誉董事');assert.equal(evaluateMembership(user).active,false);assert.equal(MEMBERSHIP_TIER_REASON_CODES[user.membershipTierReasonCode],'受邀成员');const audit=store.audits[0];assert.equal(audit.summary.membershipTierReasonCode,'invited');assert.equal(audit.summary.paymentEvidenceActivatedMembership,false)}finally{Object.assign(user,before)}});

test('member sees only own confirmed tier and renewal plan, including an individual override',async()=>{const mine=await call('/api/me',{user:'near_expiry'}),renewal=await call('/api/my/renewal-offer',{user:'near_expiry'});assert.equal(mine.payload.membershipRole,'A2 轮股东');assert.equal(renewal.payload.membershipTier.standardPriceCents,79900);assert.equal(renewal.payload.offer.offeredPriceCents,69900);assert.equal(renewal.payload.offer.priceSource,'individual_override');const safe=JSON.stringify({mine:mine.payload,renewal:renewal.payload});for(const forbidden of ['paymentSources','honoraryDirectorReasonCode','crmVerificationStatus','latestPaymentEvidenceStatus','groupStatus','amountBand'])assert.equal(safe.includes(forbidden),false,forbidden)});
