'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {OfflineMemberBindingGatewayAdapter,TRANSPORT_KIND}=require('../src/persistence/member-binding-gateway-adapter');
const {StagedMemberBindingRepository}=require('../src/persistence/member-binding-repository');
const hash=value=>String(value).repeat(64).slice(0,64);

function harness({match,entitlement,fail}={}){
  const calls=[];
  const transport={kind:TRANSPORT_KIND,
    resolveExactCrmMatch:async payload=>{calls.push(['match',payload]);if(fail==='match')throw new Error('raw CRM row');return match||{candidateCount:1,conflictStatus:'unique_candidate',selectedMatchId:'match_candidate_1',crmAccessProjection:{accountActive:true,groupStatus:'in_group',membershipMonthEffective:true,dataComplete:true,contradiction:false,riskFlags:[],entitlementProjectionReady:true,phone:'never-return'}}},
    persistCandidate:async payload=>{calls.push(['persist',payload]);if(fail==='persist')throw new Error('private store detail');return {id:'binding_candidate_1',persisted:true}},
    listPending:async payload=>{calls.push(['list',payload]);return []},
    bindIdentityIdempotently:async payload=>{calls.push(['bind',payload]);if(fail==='bind')throw new Error('private binding detail');return {idempotencyStatus:'created',subjectHash:hash('a'),memberId:'member_fixture_1'}},
    rejectCandidate:async payload=>{calls.push(['reject',payload]);return {idempotencyStatus:'created'}}
  };
  const entitlementRepository={kind:'cloudbase_gateway',resolveMemberEntitlement:async payload=>{calls.push(['entitlement',payload]);if(fail==='entitlement')throw new Error('private gateway detail');return entitlement||{subject_hash:hash('a'),member_id:'member_fixture_1',account_active:true,crm_verified:true,payment_verified:true,group_active:true,decision_active:true}}};
  const adapter=new OfflineMemberBindingGatewayAdapter({migrationBaseline:'008_admin_session_rbac',transport,entitlementRepository});
  return {calls,adapter,repository:new StagedMemberBindingRepository({adapter})};
}

test('exact CRM projection and durable candidate contract receive only keyed tokens',async()=>{const {calls,repository}=harness();const result=await repository.stageCandidate({appScopeHash:hash('a'),subjectHash:hash('b'),matchTokens:{phone:hash('c'),wechatId:hash('d'),ignored:hash('e')},evidence:{evidenceTypes:['openid_verified','phone_user_consent','raw_evidence'],phoneEvidence:'explicit_user_authorization_verified',privateNote:'never-persist'}});assert.equal(result.id,'binding_candidate_1');assert.equal(result.persisted,true);assert.equal(result.candidateCount,1);assert.equal(result.selectedMatchId,'match_candidate_1');assert.equal(result.crmAccessProjection.groupStatus,'in_group');assert.equal('phone' in result.crmAccessProjection,false);assert.deepEqual(calls.map(call=>call[0]),['match','persist']);const serialized=JSON.stringify(calls);for(const forbidden of ['ignored','never-return','raw_evidence','never-persist'])assert.equal(serialized.includes(forbidden),false);assert.equal(calls[0][1].readScope,'crm_access_projection_only');assert.equal(calls[1][1].writeScope,'binding_candidate_only');assert.deepEqual(calls[1][1].evidence.evidenceTypes,['openid_verified','phone_user_consent'])});

test('identity binding write is idempotent and 004 entitlement is re-read after each write',async()=>{const {calls,repository}=harness();const input={candidateId:'binding_candidate_1',selectedMatchId:'match_candidate_1',actorId:'system_binding_policy',reasonCode:'crm_exact_match_auto',authorizationId:null,confirmationMode:'automatic_exact_match'};let result=await repository.confirmAndReevaluate(input);assert.equal(result.bindingStatus,'auto_confirmed');assert.equal(result.entitlementActive,true);assert.equal(result.entitlementReevaluated,true);result=await repository.confirmAndReevaluate(input);const binds=calls.filter(call=>call[0]==='bind'),reads=calls.filter(call=>call[0]==='entitlement');assert.equal(binds.length,2);assert.equal(reads.length,2);assert.match(binds[0][1].idempotencyKey,/^[0-9a-f]{64}$/);assert.equal(binds[0][1].idempotencyKey,binds[1][1].idempotencyKey);assert.equal(binds[0][1].writeScope,'external_identity_binding_only');assert.deepEqual(calls.slice(0,2).map(call=>call[0]),['bind','entitlement'])});

test('inactive entitlement stays closed and mismatched or failed reads never fall back',async()=>{let harnessed=harness({entitlement:{subject_hash:hash('a'),member_id:'member_fixture_1',account_active:true,crm_verified:true,payment_verified:true,group_active:false,decision_active:false}});let result=await harnessed.repository.confirmAndReevaluate({candidateId:'binding_candidate_1',selectedMatchId:'match_candidate_1',actorId:'operator_fixture_1',reasonCode:'crm_unique_match',authorizationId:'authorization_fixture_1',confirmationMode:'operator_review'});assert.equal(result.entitlementActive,false);harnessed=harness({entitlement:{subject_hash:hash('f'),member_id:'member_fixture_1',account_active:true,crm_verified:true,payment_verified:true,group_active:true,decision_active:true}});await assert.rejects(()=>harnessed.repository.confirmAndReevaluate({candidateId:'binding_candidate_1',selectedMatchId:'match_candidate_1',actorId:'operator_fixture_1',reasonCode:'crm_unique_match',authorizationId:'authorization_fixture_1',confirmationMode:'operator_review'}),error=>error.code==='MEMBER_BINDING_REPOSITORY_UNAVAILABLE');harnessed=harness({fail:'match'});await assert.rejects(()=>harnessed.repository.stageCandidate({appScopeHash:hash('a'),subjectHash:hash('b'),matchTokens:{phone:hash('c')},evidence:{}}),error=>error.code==='MEMBER_BINDING_REPOSITORY_UNAVAILABLE'&&!error.message.includes('CRM'))});

test('ambiguous matching is sanitized and never creates an automatic selected match',async()=>{const {repository}=harness({match:{candidateCount:2,conflictStatus:'multiple_candidates',selectedMatchId:'must_not_return',crmAccessProjection:{groupStatus:'in_group',riskFlags:['identity_conflict','raw-private-flag']}}});const result=await repository.stageCandidate({appScopeHash:hash('a'),subjectHash:hash('b'),matchTokens:{phone:hash('c')},evidence:{}});assert.equal(result.selectedMatchId,null);assert.deepEqual(result.crmAccessProjection.riskFlags,['identity_conflict']);assert.equal(result.crmAccessProjection.accountActive,false);assert.equal(result.rawValuesReturned,false)});

test('adapter is offline-only, fixed to 004/008 and refuses unknown operations',async()=>{const {adapter,repository}=harness();const readiness=repository.safeReadiness();assert.equal(readiness.exactCrmMatchProjection,true);assert.equal(readiness.candidatePersistence,true);assert.equal(readiness.idempotentIdentityBinding,true);assert.equal(readiness.entitlementReevaluation,true);assert.equal(readiness.runtimeEnabled,false);assert.equal(readiness.memoryFallback,false);await assert.rejects(()=>adapter.execute('crm.write',{}),/固定白名单/);assert.throws(()=>new OfflineMemberBindingGatewayAdapter({migrationBaseline:'009_admin_governance',transport:{},entitlementRepository:{}}),/008_admin_session_rbac/)});
