'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {PassThrough}=require('node:stream');
const {resolveFormalMemberBindingHttpConfig}=require('../src/member-binding-http-config');
const {createFormalMemberBindingHttpHandler,MAX_BODY_BYTES}=require('../src/member-binding-http-handler');

const production={FORMAL_MEMBER_BINDING_ROUTES_ENABLED:'true',NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_MIGRATIONS_APPLIED:'008_admin_session_rbac',FORMAL_ADMIN_AUTH_ENABLED:'true',WECHAT_LOGIN_ENABLED:'true',MEMBER_BINDING_MODE:'crm_exact_match_or_operator_review'};
function invoke(handler,path,{method='GET',headers={},payload,raw}={}){return new Promise((resolve,reject)=>{const req=new PassThrough();req.method=method;req.url=path;req.headers={host:'localhost',...headers};const res={statusCode:200,headers:{},writeHead(status,responseHeaders){this.statusCode=status;this.headers=responseHeaders},end(chunk=''){const text=String(chunk||'');resolve({handled:true,status:this.statusCode,headers:this.headers,body:text?JSON.parse(text):{}})}};req.on('error',reject);handler(req,res).then(value=>{if(value===false)resolve({handled:false})}).catch(reject);if(raw!==undefined)req.end(raw);else if(payload!==undefined)req.end(JSON.stringify(payload));else req.end()})}
function harness(){
  const calls=[];
  const service={
    start:async input=>{calls.push(['start',input]);return {id:'binding_candidate_1',status:'bound_active',automaticMemberBinding:true,automaticMembershipActivation:false}},
    listPending:async input=>{calls.push(['list',input]);return {items:[]}},
    confirm:async input=>{calls.push(['confirm',input]);return {bindingStatus:'operator_confirmed',entitlementReevaluated:true}},
    reject:async input=>{calls.push(['reject',input]);return {status:'rejected'}}
  };
  const identityLoginService={loginWithCode:async code=>{calls.push(['session',code]);return {accessToken:'opaque-fixture-token',tokenType:'Bearer',expiresIn:900}}};
  return {calls,handler:createFormalMemberBindingHttpHandler({config:resolveFormalMemberBindingHttpConfig(production),service,identityLoginService})};
}

test('formal binding config is production-only, exact 008 and revised CRM match policy',()=>{assert.equal(resolveFormalMemberBindingHttpConfig({}).enabled,false);for(const env of [{...production,NODE_ENV:'test'},{...production,DATA_REPOSITORY:'memory_demo'},{...production,DEMO_DATA_ONLY:'true'},{...production,CLOUDBASE_PG_MIGRATIONS_APPLIED:'009_admin_governance'},{...production,FORMAL_ADMIN_AUTH_ENABLED:'false'},{...production,WECHAT_LOGIN_ENABLED:'false'},{...production,MEMBER_BINDING_MODE:'operator_confirmed_only'}])assert.throws(()=>resolveFormalMemberBindingHttpConfig(env));const config=resolveFormalMemberBindingHttpConfig(production);assert.equal(config.phoneProof,'server_verified_user_consent');assert.equal(config.safeSummary.memoryFallback,false);assert.equal(config.safeSummary.crmWrites,false)});
test('disabled binding namespace is 503 and never falls into demo routes',async()=>{const handler=createFormalMemberBindingHttpHandler({config:resolveFormalMemberBindingHttpConfig({})});let response=await invoke(handler,'/api/formal-member-binding/start',{method:'POST',payload:{code:'fixture'}});assert.equal(response.status,503);assert.equal(response.body.code,'FORMAL_MEMBER_BINDING_ROUTES_DISABLED');response=await invoke(handler,'/api/me');assert.equal(response.handled,false)});
test('start, post-bind session and 008 admin review map to separate guarded operations',async()=>{const {calls,handler}=harness();let response=await invoke(handler,'/api/formal-member-binding/start',{method:'POST',payload:{code:'login_code_fixture',phoneGrantCode:'phone_code_fixture'}});assert.equal(response.status,202);assert.equal(response.body.status,'bound_active');assert.equal(calls[0][0],'start');response=await invoke(handler,'/api/formal-member-binding/session',{method:'POST',payload:{code:'fresh_login_code'}});assert.equal(response.status,200);assert.equal(response.body.tokenType,'Bearer');response=await invoke(handler,'/api/formal-member-binding/admin/candidates?limit=10',{headers:{authorization:'Bearer admin','idempotency-key':'binding-list-1'}});assert.equal(response.status,200);response=await invoke(handler,'/api/formal-member-binding/admin/candidates/binding_candidate_1/confirm',{method:'PATCH',headers:{authorization:'Bearer admin','idempotency-key':'binding-confirm-1'},payload:{selectedMatchId:'match_candidate_1',reasonCode:'crm_unique_match'}});assert.equal(response.status,200);assert.equal(calls.at(-1)[1].selectedMatchId,'match_candidate_1');response=await invoke(handler,'/api/formal-member-binding/admin/candidates/binding_candidate_1/reject',{method:'PATCH',headers:{authorization:'Bearer admin','idempotency-key':'binding-reject-1'},payload:{reasonCode:'identity_conflict'}});assert.equal(response.status,200)});
test('client member id, invalid JSON, missing idempotency and oversized bodies fail closed',async()=>{const {calls,handler}=harness();let response=await invoke(handler,'/api/formal-member-binding/start',{method:'POST',payload:{code:'fixture',memberId:'client-claim'}});assert.equal(response.status,400);assert.equal(response.body.code,'MEMBER_BINDING_CLIENT_MEMBER_ID_FORBIDDEN');assert.equal(calls.length,0);response=await invoke(handler,'/api/formal-member-binding/start',{method:'POST',raw:'{bad'});assert.equal(response.status,400);assert.equal(response.body.code,'MEMBER_BINDING_JSON_INVALID');response=await invoke(handler,'/api/formal-member-binding/admin/candidates',{headers:{authorization:'Bearer admin'}});assert.equal(response.status,400);assert.equal(response.body.code,'ADMIN_IDEMPOTENCY_REQUIRED');response=await invoke(handler,'/api/formal-member-binding/start',{method:'POST',raw:'x'.repeat(MAX_BODY_BYTES+1)});assert.equal(response.status,413);assert.equal(response.body.code,'MEMBER_BINDING_REQUEST_TOO_LARGE')});
test('unexpected login dependency errors are normalized without upstream leakage',async()=>{const service={start:async()=>{},listPending:async()=>{},confirm:async()=>{},reject:async()=>{}},identityLoginService={loginWithCode:async()=>{throw new Error('raw secret and database row')}};const handler=createFormalMemberBindingHttpHandler({config:resolveFormalMemberBindingHttpConfig(production),service,identityLoginService}),response=await invoke(handler,'/api/formal-member-binding/session',{method:'POST',payload:{code:'fixture'}});assert.equal(response.status,503);assert.equal(response.body.code,'FORMAL_MEMBER_BINDING_UNAVAILABLE');assert.equal(JSON.stringify(response.body).includes('secret'),false)});
