'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {resolvePersistenceConfig,assertRuntimeRepositoryReady}=require('../src/persistence/config');
const {MemoryDemoRepository,PostgresRepository}=require('../src/persistence/repository');
const {loadMigrations,runMigrations}=require('../src/persistence/migrations');

const production={NODE_ENV:'production',DATA_REPOSITORY:'postgres',DATABASE_URL:'postgresql://app:fixture-only@db.internal:5432/venture',DATABASE_SSL_MODE:'verify-full',DATABASE_SCHEMA:'venture_private',DATABASE_APP_ROLE:'venture_club_app',DATABASE_MIGRATIONS_APPLIED:'002_security'};
test('memory demo is the default and production can never silently fall back',()=>{assert.equal(resolvePersistenceConfig({NODE_ENV:'test'}).mode,'memory_demo');assert.throws(()=>resolvePersistenceConfig({NODE_ENV:'production'}),/禁止使用 memory_demo/);assert.throws(()=>resolvePersistenceConfig({NODE_ENV:'test',DATABASE_URL:'postgresql:\/\/fixture'}),/未显式启用 postgres/)});
test('postgres requires complete production TLS and least-privilege configuration',()=>{for(const key of ['DATABASE_URL','DATABASE_SSL_MODE','DATABASE_SCHEMA','DATABASE_APP_ROLE','DATABASE_MIGRATIONS_APPLIED']){const env={...production};delete env[key];assert.throws(()=>resolvePersistenceConfig(env),new RegExp(key))}assert.throws(()=>resolvePersistenceConfig({...production,DATABASE_SSL_MODE:'disable'}),/verify-full/);assert.throws(()=>resolvePersistenceConfig({...production,DEMO_DATA_ONLY:'true'}),/匿名 staging/);const config=resolvePersistenceConfig(production);assert.equal(config.safeSummary.tlsVerified,true);assert.equal(JSON.stringify(config.safeSummary).includes('fixture-only'),false)});
test('phase one refuses to activate postgres-backed business APIs',()=>{const config=resolvePersistenceConfig(production);assert.throws(()=>assertRuntimeRepositoryReady(config),error=>error.code==='POSTGRES_RUNTIME_PHASE1_NOT_ACTIVATED')});
test('repository transaction commits and rolls back without exposing credentials',async()=>{const calls=[];const client={query:async sql=>{calls.push(sql);if(sql==='FAIL')throw new Error('fixture failure')},release:()=>calls.push('RELEASE')};const repo=new PostgresRepository({config:resolvePersistenceConfig(production),clientFactory:async()=>client});await repo.withTransaction(c=>c.query('SELECT 1'));assert.deepEqual(calls.slice(-2),['COMMIT','RELEASE']);calls.length=0;await assert.rejects(()=>repo.withTransaction(c=>c.query('FAIL')),/fixture failure/);assert.deepEqual(calls.slice(-2),['ROLLBACK','RELEASE']);assert.equal(JSON.stringify(repo.safeReadiness()).includes('fixture-only'),false);assert.equal(new MemoryDemoRepository({}).safeReadiness().persistent,false)});
test('migrations cover core domains and never create public tables',()=>{const migrations=loadMigrations();assert.deepEqual(migrations.map(x=>x.version),['001_core_domains','002_security']);const sql=migrations.map(x=>x.sql).join('\n');for(const table of ['crm_verifications','payment_evidence','membership_decisions','public_directory_profiles','resources','import_batches','activities','registrations','demands','demand_applications','agent_dispatches','public_profile_updates','employment_verifications','admin_roles','audit_logs'])assert.match(sql,new RegExp(`venture_private\\.${table}`));assert.doesNotMatch(sql,/CREATE TABLE(?: IF NOT EXISTS)?\s+public\./i);assert.match(sql,/REVOKE ALL ON ALL TABLES IN SCHEMA venture_private FROM PUBLIC/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/audit_logs is append-only/)});
test('migration runner records checksums and rolls back atomically',async()=>{const calls=[];const client={query:async(sql,params)=>{calls.push({sql,params});if(sql.startsWith('SELECT version'))return {rows:[]};return {rows:[]}}};const result=await runMigrations({client});assert.deepEqual(result.applied,['001_core_domains','002_security']);assert.equal(calls.at(-1).sql,'COMMIT');assert.equal(calls.filter(x=>x.sql.startsWith('INSERT INTO')).length,2);const failing={query:async sql=>{calls.push({sql});if(sql.includes('BROKEN'))throw new Error('broken');return sql.startsWith('SELECT version')?{rows:[]}:{rows:[]}}};await assert.rejects(()=>runMigrations({client:failing,migrations:[{version:'999_broken',checksum:'x',sql:'BROKEN'}]}),/broken/);assert.equal(calls.at(-1).sql,'ROLLBACK')});
