'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {PassThrough}=require('node:stream');
const {resolveProductionIntakeHttpConfig}=require('../src/production-intake-http-config');
const {createProductionIntakeHttpHandler}=require('../src/production-intake-http-handler');
const {CloudBaseAdminIdentityVerifier}=require('../src/auth/cloudbase-admin-identity-verifier');
const {ActivityPrivateProtector,CloudBaseProductionActivityRepository,ProductionActivityService}=require('../src/persistence/production-activity');

const key=Buffer.alloc(32,7).toString('base64');
const environment={NODE_ENV:'production',DEPLOYMENT_PROFILE:'cloudbase_production_intake',DEMO_DATA_ONLY:'false',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_MIGRATIONS_APPLIED:'014_production_intake_008_baseline',CRM_PERSISTENCE_MIGRATION_APPLIED:'014_production_intake_008_baseline',PRODUCTION_INTAKE_ROUTES_ENABLED:'true',FORMAL_ADMIN_AUTH_ENABLED:'true',CRM_PERSISTENT_IMPORTS_ENABLED:'true',GOVERNED_MEMBER_IMPORTS_ENABLED:'true',GOVERNED_MATERIALIZATION_ENABLED:'true',ACTIVITY_PRIVATE_LINK_ENCRYPTION_KEY:key};
const gateway={enabled:true,mode:'cloudbase_gateway',runtimeEnvironment:'production',migration:'014_production_intake_008_baseline',origin:'https://fixture.api.tcloudbasegateway.com',serverApiKey:'fixture-secret',timeoutMs:1000,maxResponseBytes:65536};
function invoke(handler,path,{method='GET',headers={},payload,raw}={}){return new Promise((resolve,reject)=>{const req=new PassThrough();req.method=method;req.url=path;req.headers={host:'localhost',...headers};const res={statusCode:200,headers:{},writeHead(status,responseHeaders){this.statusCode=status;this.headers=responseHeaders},end(chunk=''){const text=String(chunk||'');resolve({handled:true,status:this.statusCode,headers:this.headers,body:text?JSON.parse(text):{}})}};req.on('error',reject);handler(req,res).then(value=>{if(value===false)resolve({handled:false})}).catch(reject);if(raw!==undefined)req.end(raw);else if(payload!==undefined)req.end(JSON.stringify(payload));else req.end()})}

test('production intake configuration is exact, persistent and fail closed',()=>{assert.equal(resolveProductionIntakeHttpConfig({}).enabled,false);for(const changed of [{NODE_ENV:'test'},{DEPLOYMENT_PROFILE:'cloudbase_staging_demo'},{CLOUDBASE_PG_MIGRATIONS_APPLIED:'008_admin_session_rbac'},{FORMAL_ADMIN_AUTH_ENABLED:'false'},{ACTIVITY_PRIVATE_LINK_ENCRYPTION_KEY:''}])assert.throws(()=>resolveProductionIntakeHttpConfig({...environment,...changed}));const config=resolveProductionIntakeHttpConfig(environment);assert.equal(config.safeSummary.persistent,true);assert.equal(config.safeSummary.memoryFallback,false);assert.equal(JSON.stringify(config).includes(key),false)});

test('CloudBase identity verifier introspects a bounded bearer without exposing it',async()=>{const calls=[],verifier=new CloudBaseAdminIdentityVerifier({config:gateway,clock:()=>new Date('2026-09-10T10:00:00Z'),fetchImpl:async(url,options)=>{calls.push({url:String(url),options});return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({token_type:'Bearer',sub:'cloud-user-1'})}}});const token='x'.repeat(40),identity=await verifier.verify({accessToken:token,deviceId:'device-fixture-1'});assert.equal(identity.subject,'cloud-user-1');assert.equal(identity.provider,'cloudbase_user');assert.equal(calls[0].url,'https://fixture.api.tcloudbasegateway.com/auth/v1/token/introspect');assert.equal(calls[0].options.headers.authorization,`Bearer ${token}`);assert.equal(JSON.stringify(identity).includes(token),false);assert.equal(await verifier.verify({accessToken:'short',deviceId:'device-fixture-1'}),null)});

test('activity service requires public consent, encrypts private links and returns no locator',async()=>{const calls=[],repository={kind:'cloudbase_gateway',call:async input=>{calls.push(input);return {activity_id:input.activityId,status:input.status,reused:false}},list:async()=>[]},adminSessionService={authorizeAction:async()=>({userId:'admin-fixture',authorizationId:'authorization-fixture'}),resolveRequest:async()=>({verified:true,permissions:['activity.manage']})},service=new ProductionActivityService({repository,protector:new ActivityPrivateProtector(key),adminSessionService,uuid:()=> 'fixture-uuid'}),request={headers:{authorization:'Bearer opaque','idempotency-key':'activity-write-1'}};
  await assert.rejects(()=>service.upsert(request,{format:'online',status:'waiting',title:'线上主题活动',startsAt:'2026-10-01T10:00:00Z',meetingLink:'https://meeting.example/join',speakers:[{displayName:'匿名讲者'}]}),/公开授权/);
  const result=await service.upsert(request,{format:'online',status:'waiting',title:'线上主题活动',startsAt:'2026-10-01T10:00:00Z',meetingLink:'https://meeting.example/join',speakers:[{displayName:'匿名讲者',publicDisplayConsent:true}]});assert.equal(result.privateLinksReturned,false);assert.equal(JSON.stringify(result).includes('meeting.example'),false);assert.notEqual(calls[0].meetingLinkCiphertext,'https://meeting.example/join');assert.equal(JSON.stringify(calls[0].speakerSummary),JSON.stringify([{displayName:'匿名讲者',role:null,organization:null}]))});

test('activity repository uses only the fixed view and fixed RPC',async()=>{const calls=[],repository=new CloudBaseProductionActivityRepository({config:gateway,fetchImpl:async(url,options)=>{calls.push({url:String(url),options});return {ok:true,status:200,headers:{get:name=>name==='content-type'?'application/json':null},text:async()=>String(url).includes('/rpc/')?'{}':'[]'}}});await repository.list();await repository.call({authorizationId:'authorization-fixture',actorId:'admin-fixture',activityId:'activity-fixture',format:'online',title:'主题活动',description:null,startsAt:'2026-10-01T10:00:00Z',endsAt:null,registrationEndsAt:null,category:'member_event',city:null,venue:null,speakerSummary:[],participantSummary:[],status:'waiting',meetingLinkCiphertext:'cipher',replayLinkCiphertext:null,minutesLocatorCiphertext:null,recordingLocatorCiphertext:null});assert.match(calls[0].url,/venture_activities_public/);assert.match(calls[1].url,/\/rpc\/venture_upsert_activity$/);assert.equal(calls.every(call=>call.options.headers.authorization==='Bearer fixture-secret'),true)});

test('production intake HTTP namespace authenticates before preview and never falls through',async()=>{const calls=[],sessionService={login:async()=>({accessToken:'opaque-session',tokenType:'Bearer'}),resolveRequest:async()=>({verified:true,userId:'admin-fixture',permissions:['member_import.stage'],expiresAt:'2026-09-10T11:00:00Z'})},handler=createProductionIntakeHttpHandler({config:resolveProductionIntakeHttpConfig(environment),sessionService,crmCoordinator:{confirm:async input=>{calls.push(input);return {batchId:'batch-1',persistent:true}}},activityService:{list:async()=>[],upsert:async()=>({activityId:'activity-1',persistent:true})},previewBuilder:async()=>({status:'preview_complete',persisted:false})});assert.equal((await invoke(handler,'/api/unrelated')).handled,false);let result=await invoke(handler,'/api/production-admin/session',{method:'POST',payload:{accessToken:'external-token',deviceId:'device-1'}});assert.equal(result.status,201);result=await invoke(handler,'/api/production-admin/crm/preview',{method:'POST',payload:{format:'csv',dataBase64:'x'}});assert.equal(result.status,200);assert.equal(result.headers['cache-control'],'no-store');result=await invoke(handler,'/api/production-admin/crm/confirm',{method:'POST',headers:{'idempotency-key':'crm-import-1'},payload:{upload:{format:'csv',dataBase64:'x'},previewDigest:'a'.repeat(64),explicitConfirmation:true}});assert.equal(result.status,201);assert.equal(calls[0].adminSession.headers['idempotency-key'],'crm-import-1')});

test('disabled production namespace returns 503 and unexpected failures are redacted',async()=>{let result=await invoke(createProductionIntakeHttpHandler({config:{enabled:false}}),'/api/production-admin/readiness');assert.equal(result.status,503);const config=resolveProductionIntakeHttpConfig(environment),handler=createProductionIntakeHttpHandler({config,sessionService:{login:async()=>{throw new Error('raw upstream credential')}},crmCoordinator:{},activityService:{},previewBuilder:async()=>{}});result=await invoke(handler,'/api/production-admin/session',{method:'POST',payload:{}});assert.equal(result.status,500);assert.equal(JSON.stringify(result.body).includes('credential'),false)});

test('production intake health probe accepts a canary query parameter',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');assert.match(source,/requestPathname\s*=\s*new URL\(req\.url/);assert.match(source,/requestPathname\s*!==\s*'\/healthz'/);assert.doesNotMatch(source,/req\.url\s*!==\s*'\/healthz'/)});
