'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {PassThrough}=require('node:stream');
const {resolvePersistenceConfig}=require('../src/persistence/config');
const {resolvePrivateObjectStorageConfig,MAX_MVP_FILE_BYTES}=require('../src/storage/config');
const {createObjectKey,ObjectLocatorCipher,CloudBasePrivateStorageTransport}=require('../src/storage/cloudbase-private-storage');
const {CloudBaseResourceStorageRepository}=require('../src/persistence/resource-storage-repository');
const {PersistentResourceUploadService,PersistentResourceReviewService,ControlledResourceDownloadService,controlledViewState}=require('../src/storage/resource-file-service');

const key=Buffer.alloc(32,7).toString('base64');
const environment={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',CLOUDBASE_PG_ENV_ID:'fixture-env',CLOUDBASE_PG_SERVER_API_KEY:'fixture-service-role-key',CLOUDBASE_PG_REGION:'ap-shanghai',CLOUDBASE_PG_MIGRATIONS_APPLIED:'007_governed_materialization',CLOUDBASE_PG_CREDENTIAL_PURPOSE:'server_runtime',PRIVATE_STORAGE_PROVIDER:'cloudbase_pg_storage',CLOUDBASE_STORAGE_ENABLED:'true',CLOUDBASE_STORAGE_BUCKET_ID:'venture-private-resources',CLOUDBASE_STORAGE_BUCKET_PRIVATE_CONFIRMED:'true',CLOUDBASE_STORAGE_CREDENTIAL_PURPOSE:'server_runtime',CLOUDBASE_STORAGE_DOWNLOAD_MODE:'node_proxy',CLOUDBASE_STORAGE_PREVIEW_MODE:'metadata_only',OBJECT_LOCATOR_ENCRYPTION_KEY:key};
const storageConfig=()=>resolvePrivateObjectStorageConfig(environment);
const persistenceConfig=()=>resolvePersistenceConfig(environment);
const uuid='12345678-1234-4123-8123-123456789abc';
const activeMember={id:'member-fixture',userStatus:'active',status:'active',startsAt:'2020-01-01T00:00:00.000Z',endsAt:'2099-01-01T00:00:00.000Z',crmVerificationStatus:'verified',latestPaymentEvidenceStatus:'verified',latestValidPaymentAt:'2026-01-01T00:00:00.000Z',groupStatus:'in_group'};

test('private object storage config is explicit, production-only and fail closed',()=>{assert.equal(resolvePrivateObjectStorageConfig({}).enabled,false);assert.throws(()=>resolvePrivateObjectStorageConfig({CLOUDBASE_STORAGE_BUCKET_ID:'partial'}),/拒绝静默忽略/);assert.throws(()=>resolvePrivateObjectStorageConfig({...environment,DEMO_DATA_ONLY:'true'}),/匿名 staging/);assert.throws(()=>resolvePrivateObjectStorageConfig({...environment,CLOUDBASE_STORAGE_BUCKET_PRIVATE_CONFIRMED:'false'}),/private/);assert.throws(()=>resolvePrivateObjectStorageConfig({...environment,CLOUDBASE_STORAGE_DOWNLOAD_MODE:'signed_url'}),/node_proxy/);assert.throws(()=>resolvePrivateObjectStorageConfig({...environment,CLOUDBASE_STORAGE_MAX_FILE_BYTES:String(MAX_MVP_FILE_BYTES+1)}),/整数/);const config=storageConfig();assert.equal(config.safeSummary.multipartEnabled,false);assert.equal(config.safeSummary.previewMode,'metadata_only');assert.equal(JSON.stringify(config.safeSummary).includes('fixture-service-role-key'),false);assert.equal(JSON.stringify(config.safeSummary).includes(key),false)});

test('object keys are server-generated and never derived from user filenames',()=>{const objectKey=createObjectKey({extension:'.pdf',now:new Date('2026-08-05T00:00:00Z'),randomUUID:()=>uuid});assert.equal(objectKey,`resources/2026/08/${uuid}.pdf`);assert.equal(objectKey.includes('匿名报告'),false);assert.throws(()=>createObjectKey({extension:'.exe',randomUUID:()=>uuid}),/白名单/)});

test('locator encryption is authenticated and never returns bucket or key in ciphertext',()=>{const config=storageConfig(),cipher=new ObjectLocatorCipher(config),objectKey=`resources/2026/08/${uuid}.pdf`,sealed=cipher.seal(objectKey);assert.match(sealed.referenceHash,/^[0-9a-f]{64}$/);assert.equal(sealed.ciphertext.includes(objectKey),false);assert.equal(sealed.ciphertext.includes(config.bucketId),false);assert.equal(cipher.open(sealed.ciphertext),objectKey);const parts=sealed.ciphertext.split('.');parts[2]=`${parts[2][0]==='A'?'B':'A'}${parts[2].slice(1)}`;assert.equal(cipher.open(parts.join('.')),null)});

test('storage transport only uploads validated bytes to the fixed private bucket',async()=>{const calls=[],config=storageConfig(),transport=new CloudBasePrivateStorageTransport({config,fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});return {ok:true,status:200,headers:{get:()=>null}}}}),objectKey=`resources/2026/08/${uuid}.pdf`,bytes=Buffer.from('%PDF-1.4\nsynthetic');await transport.uploadObject({objectKey,bytes,mimeType:'application/pdf',sizeBytes:bytes.length});assert.equal(calls[0].url.origin,'https://fixture-env.api.tcloudbasegateway.com');assert.equal(calls[0].url.pathname,`/v1/storages/object/venture-private-resources/resources/2026/08/${uuid}.pdf`);assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].options.redirect,'error');assert.equal(calls[0].options.headers.authorization,'Bearer fixture-service-role-key');assert.equal(calls[0].url.href.includes('fixture-service-role-key'),false);await assert.rejects(()=>transport.uploadObject({objectKey:'other/arbitrary.pdf',bytes,mimeType:'application/pdf',sizeBytes:bytes.length}),/对象键/);assert.equal(calls.length,1)});

test('private downloads are proxied as bounded streams and invalid upstream metadata fails closed',async()=>{const objectKey=`resources/2026/08/${uuid}.pdf`,body=new PassThrough();body.end(Buffer.from('synthetic-pdf-body'));const good=new CloudBasePrivateStorageTransport({config:storageConfig(),fetchImpl:async()=>({ok:true,status:200,body,headers:{get:name=>name==='content-length'?'18':name==='content-type'?'application/pdf':name==='etag'?'fixture-etag':null}})});const opened=await good.openObject(objectKey),chunks=[];for await(const chunk of opened.body)chunks.push(chunk);assert.equal(Buffer.concat(chunks).toString(),'synthetic-pdf-body');assert.equal(opened.contentType,'application/pdf');assert.equal('url' in opened,false);const badBody=new PassThrough();badBody.end('x');const bad=new CloudBasePrivateStorageTransport({config:storageConfig(),fetchImpl:async()=>({ok:true,status:200,body:badBody,headers:{get:name=>name==='content-type'?'text/html':null}})});await assert.rejects(()=>bad.openObject(objectKey),error=>error.code==='PRIVATE_STORAGE_UNAVAILABLE')});

test('resource persistence adapter has fixed RPC and view allowlists',async()=>{const calls=[],repository=new CloudBaseResourceStorageRepository({config:persistenceConfig(),fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});return {ok:true,status:200,headers:{get:name=>name==='content-type'?'application/json':null},text:async()=>JSON.stringify({status:'initiated'})}}});await repository.beginUpload({intentId:'intent-fixture',resourceId:'resource-fixture',importItemId:'item-fixture',batchId:'batch-fixture',actorId:'admin-fixture',title:'匿名报告',summary:'匿名摘要',tags:['行业'],type:'industry_report',mobileSection:'reports_digest',extension:'.pdf',mimeType:'application/pdf',sizeBytes:10,sha256:'a'.repeat(64),downloadEnabled:true});assert.equal(calls[0].url.pathname,'/v1/rdb/rest/rpc/venture_begin_resource_upload');assert.equal(calls[0].options.method,'POST');assert.equal(JSON.parse(calls[0].options.body).p_title,'匿名报告');await assert.rejects(()=>repository.callRpc('arbitrary_sql',{}),/不在服务端白名单/);assert.equal(calls.length,1)});

test('persistent upload succeeds only after intent, object and metadata commit',async()=>{const events=[],config=storageConfig(),cipher=new ObjectLocatorCipher(config),repository={kind:'cloudbase_gateway',beginUpload:async()=>events.push('begin'),completeUpload:async input=>{events.push('complete');assert.equal(input.objectRefCiphertext.includes('resources/'),false)},failUpload:async()=>events.push('fail')},storage={uploadObject:async input=>{events.push('upload');assert.equal(input.objectKey.includes('synthetic-report'),false);assert.equal(input.mimeType,'application/pdf')},deleteObject:async()=>events.push('delete')},service=new PersistentResourceUploadService({storageConfig:config,repository,storageTransport:storage,locatorCipher:cipher,adminIdentityProvider:'external_session',randomUUID:()=>uuid});const result=await service.upload({actorId:'admin-fixture',metadata:{title:'匿名报告',summary:'匿名摘要',tags:'行业，报告',section:'reports_digest',downloadEnabled:true},file:{filename:'synthetic-report.pdf',mimeType:'application/pdf',bytes:Buffer.from('%PDF-1.4\nsynthetic')}});assert.deepEqual(events,['begin','upload','complete']);assert.equal(result.status,'pending_review');assert.equal(result.downloadEnabled,false);assert.equal(result.requestedDownloadEnabled,true);assert.equal(result.previewStatus,'preview_not_configured');assert.equal(result.storageLocatorReturned,false)});

test('upload failures never fall back to memory and compensate after metadata failure',async()=>{const events=[],config=storageConfig(),cipher=new ObjectLocatorCipher(config),repository={kind:'cloudbase_gateway',beginUpload:async()=>events.push('begin'),completeUpload:async()=>{events.push('complete');throw new Error('db down')},failUpload:async()=>events.push('fail')},storage={uploadObject:async()=>events.push('upload'),deleteObject:async()=>events.push('delete')},service=new PersistentResourceUploadService({storageConfig:config,repository,storageTransport:storage,locatorCipher:cipher,adminIdentityProvider:'external_session',randomUUID:()=>uuid});await assert.rejects(()=>service.upload({actorId:'admin-fixture',metadata:{title:'匿名报告',section:'reports_digest'},file:{filename:'fixture.pdf',mimeType:'application/pdf',bytes:Buffer.from('%PDF-1.4\nsynthetic')}}),error=>error.code==='RESOURCE_FILE_SERVICE_UNAVAILABLE');assert.deepEqual(events,['begin','upload','complete','delete','fail'])});

test('download gates run before locator lookup and storage fetch',async()=>{const events=[],config=storageConfig(),cipher=new ObjectLocatorCipher(config),objectKey=`resources/2026/08/${uuid}.pdf`,sealed=cipher.seal(objectKey),record={resource_status:'published',rights_review_status:'approved',download_enabled:true,file_status:'ready',file_extension:'pdf',size_bytes:10,sha256:'a'.repeat(64),object_ref_ciphertext:sealed.ciphertext};const repository={kind:'cloudbase_gateway',resolveDownloadObject:async()=>{events.push('lookup');return record}},storage={openObject:async(key,expected)=>{events.push('storage');assert.equal(expected.expectedSizeBytes,10);assert.equal(expected.expectedSha256,'a'.repeat(64));return {body:{stream:true},contentType:'application/pdf',contentLength:10}}};const denied=new ControlledResourceDownloadService({repository,storageTransport:storage,locatorCipher:cipher,memberResolver:async()=>({...activeMember,groupStatus:'left_group'}),identityProvider:'external_verified_session',downloadMode:'node_proxy'});await assert.rejects(()=>denied.open({},'resource-fixture'),error=>error.code==='MEMBERSHIP_REQUIRED');assert.deepEqual(events,[]);const allowed=new ControlledResourceDownloadService({repository,storageTransport:storage,locatorCipher:cipher,memberResolver:async()=>{events.push('identity');return activeMember},identityProvider:'external_verified_session',downloadMode:'node_proxy'});const result=await allowed.open({},'resource-fixture');assert.deepEqual(events,['identity','lookup','storage']);assert.equal(result.proxied,true);assert.equal(result.temporaryUrlReturned,false);assert.equal(result.storageLocatorReturned,false)});

test('downloadEnabled false and preview-not-configured never touch private bytes',async()=>{let fetched=false;const config=storageConfig(),cipher=new ObjectLocatorCipher(config),repository={kind:'cloudbase_gateway',resolveDownloadObject:async()=>({resource_status:'published',rights_review_status:'approved',download_enabled:false,file_status:'ready',file_extension:'pdf',size_bytes:10,sha256:'a'.repeat(64),object_ref_ciphertext:cipher.seal(`resources/2026/08/${uuid}.pdf`).ciphertext})},service=new ControlledResourceDownloadService({repository,storageTransport:{openObject:async()=>{fetched=true}},locatorCipher:cipher,memberResolver:async()=>activeMember,identityProvider:'external_verified_session',downloadMode:'node_proxy'});await assert.rejects(()=>service.open({},'resource-fixture'),error=>error.code==='RESOURCE_DOWNLOAD_NOT_AVAILABLE');assert.equal(fetched,false);const view=controlledViewState({id:'resource-fixture',title:'匿名报告',summary:'安全摘要',tags:['行业'],download_enabled:false,object_ref_ciphertext:'must-not-leak'});assert.equal(view.previewAvailable,false);assert.match(view.previewNotice,/待配置/);assert.equal(JSON.stringify(view).includes('must-not-leak'),false)});

test('persistent review requires copyright and file security gates',async()=>{let calls=0;const service=new PersistentResourceReviewService({repository:{kind:'cloudbase_gateway',reviewResource:async()=>{calls++;return {resource_id:'resource-fixture',status:'published',download_enabled:true}}},adminIdentityProvider:'external_session',randomUUID:()=>uuid});await assert.rejects(()=>service.review({resourceId:'resource-fixture',reviewerId:'admin-fixture',decision:'publish',copyrightConfirmed:false,securityReviewStatus:'manual_confirmed',downloadEnabled:true}),error=>error.code==='RESOURCE_REVIEW_GATES_INCOMPLETE');assert.equal(calls,0);const result=await service.review({resourceId:'resource-fixture',reviewerId:'admin-fixture',decision:'publish',copyrightConfirmed:true,securityReviewStatus:'manual_confirmed',downloadEnabled:true});assert.equal(calls,1);assert.equal(result.previewStatus,'preview_not_configured');assert.equal(result.downloadEnabled,true);assert.equal(result.storageLocatorReturned,false)});
