'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {resolveWechatIdentityConfig}=require('../src/auth/wechat-config');
const {WechatCodeExchangeClient}=require('../src/auth/wechat-identity');
const {WechatOfficialJsonTransport,WechatAccessTokenProvider,WechatPhoneNumberExchangeClient,createWechatOfficialProviders}=require('../src/auth/wechat-official-provider');
const key=value=>Buffer.alloc(32,value).toString('base64');
const environment={NODE_ENV:'production',DATA_REPOSITORY:'cloudbase_gateway',WECHAT_LOGIN_ENABLED:'true',MEMBER_IDENTITY_PROVIDER:'external_verified_session',MEMBER_BINDING_MODE:'crm_exact_match_or_operator_review',MEMBER_SESSION_REVOCATION_STORE:'external_persistent',WECHAT_MINIPROGRAM_APP_ID:'wx1234567890abcdef',WECHAT_MINIPROGRAM_APP_SECRET:'fixture-server-secret',WECHAT_IDENTITY_SUBJECT_HMAC_KEY:key(1),MEMBER_SESSION_ENCRYPTION_KEY:key(2),MEMBER_SESSION_ISSUER:'fixture-issuer',MEMBER_SESSION_AUDIENCE:'fixture-audience'};
const config=overrides=>resolveWechatIdentityConfig({...environment,...overrides});
const response=value=>({ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(value)});

test('official provider config validates bounded network controls without exposing secrets',()=>{const resolved=config({WECHAT_API_TIMEOUT_MS:'4000',WECHAT_API_MAX_RESPONSE_BYTES:'8192',WECHAT_ACCESS_TOKEN_REFRESH_SKEW_SECONDS:'90'});assert.equal(resolved.apiTimeoutMs,4000);assert.equal(resolved.apiMaxResponseBytes,8192);assert.equal(resolved.accessTokenRefreshSkewSeconds,90);assert.equal(JSON.stringify(resolved.safeSummary).includes('fixture-server-secret'),false);for(const [key,value] of [['WECHAT_API_TIMEOUT_MS','999'],['WECHAT_API_MAX_RESPONSE_BYTES','70000'],['WECHAT_ACCESS_TOKEN_REFRESH_SKEW_SECONDS','10']])assert.throws(()=>config({[key]:value}),new RegExp(key))});

test('code2Session uses the fixed official endpoint and strips session/profile claims',async()=>{let request;const client=new WechatCodeExchangeClient({config:config(),fetchImpl:async(url,options)=>{request={url:new URL(url),options};return response({openid:'openid-fixture',session_key:'discard',nickName:'discard',phoneNumber:'discard'})}});const result=await client.exchange('login_code_fixture');assert.deepEqual(result,{subjectType:'openid',subject:'openid-fixture'});assert.equal(request.url.origin,'https://api.weixin.qq.com');assert.equal(request.url.pathname,'/sns/jscode2session');assert.equal(request.options.method,'GET');assert.equal(JSON.stringify(result).includes('session_key'),false)});

test('phone code exchange gets a server token, caches it, and returns no token metadata',async()=>{const calls=[];let now=1_800_000_000_000;const identityConfig=config();const transport=new WechatOfficialJsonTransport({fetchImpl:async(url,options)=>{const parsed=new URL(url);calls.push({url:parsed,options});if(parsed.pathname==='/cgi-bin/token')return response({access_token:'server-access-token-fixture',expires_in:7200});return response({errcode:0,phone_info:{phoneNumber:'13800000000',purePhoneNumber:'13800000000',countryCode:'86',watermark:{appid:'discard'}}})},timeoutMs:identityConfig.apiTimeoutMs,maxResponseBytes:identityConfig.apiMaxResponseBytes});const accessTokenProvider=new WechatAccessTokenProvider({config:identityConfig,transport,clock:()=>now});const verifier=new WechatPhoneNumberExchangeClient({config:identityConfig,transport,accessTokenProvider});const first=await verifier.verify('phone_code_fixture_1'),second=await verifier.verify('phone_code_fixture_2');assert.deepEqual(first,{verified:true,phoneNumber:'13800000000'});assert.deepEqual(second,first);assert.equal(calls.filter(call=>call.url.pathname==='/cgi-bin/token').length,1);assert.equal(calls.filter(call=>call.url.pathname==='/wxa/business/getuserphonenumber').length,2);assert.deepEqual(JSON.parse(calls[1].options.body),{code:'phone_code_fixture_1'});for(const sensitive of ['server-access-token-fixture','fixture-server-secret','countryCode','watermark'])assert.equal(JSON.stringify(first).includes(sensitive),false);now+=7_100_000;await verifier.verify('phone_code_fixture_3');assert.equal(calls.filter(call=>call.url.pathname==='/cgi-bin/token').length,2)});

test('invalid grants, timeouts, upstream errors and oversized responses fail closed without secret leakage',async()=>{const identityConfig=config();let calls=0;let transport=new WechatOfficialJsonTransport({fetchImpl:async()=>{calls++;return response({})}}),tokenProvider=new WechatAccessTokenProvider({config:identityConfig,transport}),verifier=new WechatPhoneNumberExchangeClient({config:identityConfig,transport,accessTokenProvider:tokenProvider});await assert.rejects(()=>verifier.verify('bad code'),error=>error.code==='WECHAT_GRANT_CODE_INVALID'&&error.statusCode===400);assert.equal(calls,0);transport=new WechatOfficialJsonTransport({fetchImpl:async()=>{const error=new Error('raw upstream with fixture-server-secret');error.name='AbortError';throw error}});const timeoutError=await transport.request({url:new URL('https://api.weixin.qq.com/cgi-bin/token')}).catch(error=>error);assert.equal(timeoutError.code,'WECHAT_PROVIDER_TIMEOUT');assert.doesNotMatch(JSON.stringify(timeoutError),/fixture-server-secret|raw upstream/);transport=new WechatOfficialJsonTransport({fetchImpl:async()=>({ok:true,headers:{get:name=>name==='content-length'?'99999':null},text:async()=>{throw new Error('must not read')}})});await assert.rejects(()=>transport.request({url:new URL('https://api.weixin.qq.com/cgi-bin/token')}),error=>error.code==='WECHAT_PROVIDER_RESPONSE_TOO_LARGE')});

test('provider factory is injectable and never enables runtime routes',()=>{const providers=createWechatOfficialProviders({config:config(),fetchImpl:async()=>response({})});assert.equal(providers.phoneGrantVerifier.safeReadiness().rawPhoneReturnedToClient,false);assert.equal(providers.accessTokenProvider.safeReadiness().credentialsExposed,false);assert.equal('routeHandler' in providers,false)});
