-- Read-only catalog verification. Run only after the future package is deployed.
SELECT
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='004_wechat_identity_entitlement' AND checksum='89651f91578a44d1f5fd78e8039c7ded587bbfae3a18764ee4bb3b2090d5a621') AS canonical_004_verified,
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='008_admin_session_rbac' AND checksum='1d29f1997e3d63322ae56a0fef78b559d41028e2d278527ffdc0d51e1652bd3d') AS canonical_008_verified,
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='012_member_binding_rpc_008_baseline' AND checksum='89d8779f3752fdfd6a1cebcbf131b6291ff9f64a3a14b8b11a2eab1b30abf50e') AS future_012_recorded,
  to_regclass('venture_private.member_binding_match_tokens') IS NOT NULL AS match_tokens_private,
  to_regclass('venture_private.member_binding_match_options') IS NOT NULL AS match_options_private,
  to_regclass('venture_private.member_binding_candidates') IS NOT NULL AS candidates_private,
  to_regclass('venture_private.member_binding_idempotency') IS NOT NULL AS idempotency_private,
  to_regclass('venture_private.member_binding_token_idempotency') IS NOT NULL AS token_idempotency_private,
  to_regprocedure('public.venture_member_binding_resolve_exact_match(jsonb)') IS NOT NULL AS exact_match_rpc_exists,
  to_regprocedure('public.venture_member_binding_persist_candidate(jsonb)') IS NOT NULL AS candidate_rpc_exists,
  to_regprocedure('public.venture_member_binding_list_pending(jsonb)') IS NOT NULL AS review_rpc_exists,
  to_regprocedure('public.venture_member_binding_bind_and_recompute(jsonb)') IS NOT NULL AS bind_rpc_exists,
  to_regprocedure('public.venture_member_binding_reject_candidate(jsonb)') IS NOT NULL AS reject_rpc_exists,
  to_regprocedure('public.venture_member_binding_replace_confirmed_phone_tokens(jsonb)') IS NOT NULL AS token_provision_rpc_exists,
  has_function_privilege('service_role','public.venture_member_binding_resolve_exact_match(jsonb)','EXECUTE') AS service_role_exact_match,
  has_function_privilege('service_role','public.venture_member_binding_persist_candidate(jsonb)','EXECUTE') AS service_role_candidate,
  has_function_privilege('service_role','public.venture_member_binding_list_pending(jsonb)','EXECUTE') AS service_role_review,
  has_function_privilege('service_role','public.venture_member_binding_bind_and_recompute(jsonb)','EXECUTE') AS service_role_bind,
  has_function_privilege('service_role','public.venture_member_binding_reject_candidate(jsonb)','EXECUTE') AS service_role_reject,
  has_function_privilege('service_role','public.venture_member_binding_replace_confirmed_phone_tokens(jsonb)','EXECUTE') AS service_role_token_provision,
  NOT has_function_privilege('anon','public.venture_member_binding_resolve_exact_match(jsonb)','EXECUTE') AS anon_exact_match_denied,
  NOT has_function_privilege('authenticated','public.venture_member_binding_resolve_exact_match(jsonb)','EXECUTE') AS authenticated_exact_match_denied,
  NOT has_function_privilege('anon','public.venture_member_binding_bind_and_recompute(jsonb)','EXECUTE') AS anon_bind_denied,
  NOT has_function_privilege('authenticated','public.venture_member_binding_bind_and_recompute(jsonb)','EXECUTE') AS authenticated_bind_denied,
  NOT has_function_privilege('anon','public.venture_member_binding_replace_confirmed_phone_tokens(jsonb)','EXECUTE') AS anon_token_provision_denied,
  NOT has_function_privilege('authenticated','public.venture_member_binding_replace_confirmed_phone_tokens(jsonb)','EXECUTE') AS authenticated_token_provision_denied,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.member_binding_match_tokens'::regclass) AS match_tokens_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.member_binding_match_options'::regclass) AS match_options_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.member_binding_candidates'::regclass) AS candidates_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.member_binding_idempotency'::regclass) AS idempotency_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.member_binding_token_idempotency'::regclass) AS token_idempotency_rls_forced;
