-- Read-only catalog verification. Run only after the future package is deployed.
SELECT
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='004_wechat_identity_entitlement' AND checksum='89651f91578a44d1f5fd78e8039c7ded587bbfae3a18764ee4bb3b2090d5a621') AS canonical_004_verified,
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='008_admin_session_rbac' AND checksum='1d29f1997e3d63322ae56a0fef78b559d41028e2d278527ffdc0d51e1652bd3d') AS canonical_008_verified,
  EXISTS(SELECT 1 FROM venture_private.schema_migrations WHERE version='013_agent_rpc_008_baseline' AND checksum='cdbb91f952fea9f0aec41e2bfeadce0bb149cac1f5d56fad1413653128e2e46d') AS future_013_recorded,
  to_regclass('venture_private.agent_demand_intakes') IS NOT NULL AS demand_intakes_private,
  to_regclass('venture_private.agent_application_statements') IS NOT NULL AS application_statements_private,
  to_regclass('venture_private.agent_directional_candidates') IS NOT NULL AS directional_candidates_private,
  to_regclass('venture_private.agent_mutation_idempotency') IS NOT NULL AS mutation_idempotency_private,
  to_regprocedure('public.venture_agent_list_published_opportunities(jsonb)') IS NOT NULL AS list_rpc_exists,
  to_regprocedure('public.venture_agent_stage_demand_review(jsonb)') IS NOT NULL AS stage_demand_rpc_exists,
  to_regprocedure('public.venture_agent_stage_application_review(jsonb)') IS NOT NULL AS stage_application_rpc_exists,
  to_regprocedure('public.venture_agent_record_demand_review(jsonb)') IS NOT NULL AS review_demand_rpc_exists,
  to_regprocedure('public.venture_agent_upsert_directional_candidate(jsonb)') IS NOT NULL AS directional_candidate_rpc_exists,
  to_regprocedure('public.venture_agent_record_application_dispatch(jsonb)') IS NOT NULL AS dispatch_rpc_exists,
  to_regprocedure('public.venture_agent_record_owner_decision(jsonb)') IS NOT NULL AS owner_decision_rpc_exists,
  to_regprocedure('public.venture_agent_record_operator_relay(jsonb)') IS NOT NULL AS operator_relay_rpc_exists,
  has_function_privilege('service_role','public.venture_agent_list_published_opportunities(jsonb)','EXECUTE') AS service_role_list,
  has_function_privilege('service_role','public.venture_agent_stage_demand_review(jsonb)','EXECUTE') AS service_role_stage_demand,
  has_function_privilege('service_role','public.venture_agent_stage_application_review(jsonb)','EXECUTE') AS service_role_stage_application,
  has_function_privilege('service_role','public.venture_agent_record_demand_review(jsonb)','EXECUTE') AS service_role_review,
  has_function_privilege('service_role','public.venture_agent_upsert_directional_candidate(jsonb)','EXECUTE') AS service_role_directional,
  has_function_privilege('service_role','public.venture_agent_record_application_dispatch(jsonb)','EXECUTE') AS service_role_dispatch,
  has_function_privilege('service_role','public.venture_agent_record_owner_decision(jsonb)','EXECUTE') AS service_role_owner_decision,
  has_function_privilege('service_role','public.venture_agent_record_operator_relay(jsonb)','EXECUTE') AS service_role_operator_relay,
  (SELECT count(*)=8 FROM pg_proc procedure JOIN pg_namespace namespace ON namespace.oid=procedure.pronamespace
    WHERE namespace.nspname='public' AND procedure.proname=ANY(ARRAY[
      'venture_agent_list_published_opportunities','venture_agent_stage_demand_review',
      'venture_agent_stage_application_review','venture_agent_record_demand_review',
      'venture_agent_upsert_directional_candidate','venture_agent_record_application_dispatch',
      'venture_agent_record_owner_decision','venture_agent_record_operator_relay'
    ]) AND procedure.prosecdef AND 'search_path=venture_private,pg_catalog'=ANY(coalesce(procedure.proconfig,'{}'::text[]))) AS all_rpcs_security_definer_with_fixed_path,
  NOT has_function_privilege('anon','public.venture_agent_list_published_opportunities(jsonb)','EXECUTE') AS anon_list_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_list_published_opportunities(jsonb)','EXECUTE') AS authenticated_list_denied,
  NOT has_function_privilege('anon','public.venture_agent_stage_demand_review(jsonb)','EXECUTE') AS anon_stage_demand_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_stage_demand_review(jsonb)','EXECUTE') AS authenticated_stage_demand_denied,
  NOT has_function_privilege('anon','public.venture_agent_stage_application_review(jsonb)','EXECUTE') AS anon_stage_application_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_stage_application_review(jsonb)','EXECUTE') AS authenticated_stage_application_denied,
  NOT has_function_privilege('anon','public.venture_agent_record_demand_review(jsonb)','EXECUTE') AS anon_review_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_record_demand_review(jsonb)','EXECUTE') AS authenticated_review_denied,
  NOT has_function_privilege('anon','public.venture_agent_upsert_directional_candidate(jsonb)','EXECUTE') AS anon_directional_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_upsert_directional_candidate(jsonb)','EXECUTE') AS authenticated_directional_denied,
  NOT has_function_privilege('anon','public.venture_agent_record_application_dispatch(jsonb)','EXECUTE') AS anon_dispatch_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_record_application_dispatch(jsonb)','EXECUTE') AS authenticated_dispatch_denied,
  NOT has_function_privilege('anon','public.venture_agent_record_owner_decision(jsonb)','EXECUTE') AS anon_owner_decision_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_record_owner_decision(jsonb)','EXECUTE') AS authenticated_owner_decision_denied,
  NOT has_function_privilege('anon','public.venture_agent_record_operator_relay(jsonb)','EXECUTE') AS anon_relay_denied,
  NOT has_function_privilege('authenticated','public.venture_agent_record_operator_relay(jsonb)','EXECUTE') AS authenticated_relay_denied,
  position('idempotency_key_hash' in pg_get_functiondef('public.venture_agent_stage_demand_review(jsonb)'::regprocedure))>0 AS member_write_idempotency_checked,
  position('permission_code=''demand.review''' in pg_get_functiondef('venture_private.consume_agent_authorization(text,text)'::regprocedure))>0 AS demand_review_authorization_checked,
  position('interval ''14 days''' in pg_get_functiondef('public.venture_agent_upsert_directional_candidate(jsonb)'::regprocedure))>0 AS directional_14_day_window_checked,
  position('jsonb_array_length(dimensions) NOT BETWEEN 3 AND 4' in pg_get_functiondef('public.venture_agent_upsert_directional_candidate(jsonb)'::regprocedure))>0 AS directional_three_of_four_checked,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.demands'::regclass) AS demands_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.demand_applications'::regclass) AS applications_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.agent_dispatches'::regclass) AS dispatches_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.agent_demand_intakes'::regclass) AS demand_intakes_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.agent_application_statements'::regclass) AS statements_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.agent_directional_candidates'::regclass) AS candidates_rls_forced,
  (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='venture_private.agent_mutation_idempotency'::regclass) AS idempotency_rls_forced;
