const {request,formalRequest}=require('../../utils/api');
const types=[['all','全部'],['investment','投资'],['fundraising','融资'],['ma','并购'],['recruitment','招聘'],['business_attraction','招商']];
const modes=[{key:'redacted_public',label:'脱敏公开：仅安全摘要进入机会流'},{key:'private_match',label:'仅私密匹配：不进入信息流'},{key:'full_public',label:'完整公开：仅审核后的公开字段'}];
const recorder=wx.getRecorderManager();
const formalMode=()=>{const runtime=getApp().globalData.runtime;return runtime.identityMode==='formal_member_binding'&&runtime.formalBindingEnabled===true};
Page({
  data:{types:types.map(([key,label])=>({key,label})),modes,modeIndex:0,active:'all',all:[],items:[],requests:[],who:'',why:'',target:'',recording:false,voiceNotice:'语音上传与转写待正式微信和 ASR 配置'},
  onLoad(){recorder.onStop(()=>{this.setData({recording:false});if(formalMode())return wx.showModal({title:'语音能力待配置',content:'正式 ASR 尚未配置；录音不会上传或伪装成已转写。',showCancel:false});request('/api/agent-voice-sessions',{method:'POST',data:{recordedLocally:true}}).catch(e=>wx.showModal({title:'语音能力待配置',content:e.message,showCancel:false}))});recorder.onError(()=>{this.setData({recording:false});wx.showToast({title:'请检查微信录音授权',icon:'none'})})},
  onShow(){this.load()},
  load(){if(formalMode())return formalRequest('/api/formal-agent/opportunities',{auth:true}).then(result=>{this.setData({all:result.items||[],requests:[],voiceNotice:'正式 ASR 尚未配置；当前只接受文字需求。'});this.filter()}).catch(e=>wx.showToast({title:e.message,icon:'none'}));Promise.all([request('/api/opportunities'),request('/api/my/agent-match-requests'),request('/api/member-capabilities')]).then(([all,requests,c])=>{this.setData({all,requests,voiceNotice:c.notices.voice});this.filter()}).catch(e=>wx.showToast({title:e.message,icon:'none'}))},
  input(e){this.setData({[e.currentTarget.dataset.field]:e.detail.value})},selectMode(e){this.setData({modeIndex:Number(e.detail.value)})},select(e){this.setData({active:e.currentTarget.dataset.key});this.filter()},filter(){this.setData({items:this.data.active==='all'?this.data.all:this.data.all.filter(x=>x.type===this.data.active)})},
  submit(){const category=this.data.active==='all'?'investment':this.data.active,distributionMode=this.data.modes[this.data.modeIndex].key,formal=formalMode(),path=formal?'/api/formal-agent/demands':'/api/agent-match-requests',data=formal?{type:category,who:this.data.who,why:this.data.why,target:this.data.target,distributionMode}:{inputMode:'text',category,who:this.data.who,why:this.data.why,target:this.data.target,distributionMode},send=formal?formalRequest(path,{method:'POST',data,auth:true}):request(path,{method:'POST',data});send.then(x=>{wx.showModal({title:'已进入人工审核',content:x.notice||'需求只进入人工审核，不会自动发布、推送或披露联系人。',showCancel:false});this.setData({who:'',why:'',target:''});this.load()}).catch(e=>wx.showToast({title:e.message,icon:'none'}))},
  record(){if(this.data.recording){recorder.stop();return}wx.authorize({scope:'scope.record',success:()=>{this.setData({recording:true});recorder.start({duration:60000,format:'mp3'})},fail:()=>wx.showModal({title:'需要录音授权',content:'请在微信设置中开启录音权限；录音上传与 ASR 仍需正式配置。',showCancel:false})})},
  apply(e){const id=e.currentTarget.dataset.id;wx.showModal({title:'第一步：我是谁',editable:true,placeholderText:'角色和相关背景',success:a=>{if(!a.confirm||!a.content)return;wx.showModal({title:'第二步：为什么联系',editable:true,placeholderText:'具体匹配理由',success:b=>{if(!b.confirm||!b.content)return;wx.showModal({title:'第三步：讨论什么',editable:true,placeholderText:'具体事项',success:c=>{if(!c.confirm||!c.content)return;const path=formalMode()?`/api/formal-agent/demands/${id}/applications`:`/api/demands/${id}/apply`,options={method:'POST',data:{who:a.content,why:b.content,topic:c.content},auth:true},send=formalMode()?formalRequest(path,options):request(path,options);send.then(()=>wx.showToast({title:'已提交'})).catch(x=>wx.showToast({title:x.message,icon:'none'}))}})}})}})}
});
