-- Compatibility notice: the old public-schema draft is intentionally retired.
-- Do not run this file. Canonical, ordered migrations live in server/db/migrations/ and
-- must be applied by the reviewed server-side migration runner with a migration-only role.
-- The application never creates tables on startup and never exposes venture_private via PostgREST.
